### ISSUE TITLE
Gmail login is not working with 5.5.0

### ISSUE THREAD

**Issue by adithshenoy** [getferdi/ferdi#1018]
**Bug description:**
After installing 5.5.0, on clicking gmail, it shows the sign in page. On clicking login, it navigates to the browser and then logs in there and just stops. The service in Ferdi is still in Sign in state

**Steps to reproduce:**
1. Go to 'Gmail'
2. Click on 'Sign In'
3. Sign in in the browser
4. Check Ferdi, it still is in same sign in page stuck asking to sign in

**Expected behavior**
Gmail should load on Ferdi and show the mails

**Environment:**

- Operating System: MacOS
- Ferdi Version: 5.5.0
- Server: Ferdi

**Comment by marcolussetti** [comment]
@adithshenoy: no access to a Mac to reproduce (cannot on Windows)

- could you please toggle Developer Tools (`Ctrl+Alt+I` or whatever is appropriate for your platform, `View -> Toggle Developer Tools`)
- Go to the "Console Tab"
- Reload (`Ctrl+R`)
- See if there are any relevant error (red) messages that could help us debug this?

**Comment by kytwb** [comment]
This is a [known issue](https://github.com/getferdi/ferdi/issues/264) that has been fixed in the most recent releases. Unfortunately, the latest stable release (5.5.0) is a bit behind, that's why we have been speeding things up to release 5.6.0.  
In the meantime, please try with one of the latest [beta](https://github.com/getferdi/ferdi/releases/tag/5.6.0-beta.2)/[nightly](https://github.com/getferdi/nightlies/releases).
