### ISSUE TITLE
Allow spell checking for multiple languages

### ISSUE THREAD

**Issue by ivanddiaz** [getferdi/ferdi#1046]
As ElectronJS has the option for enable multiple languages on the spell checker like this

> // Sets the spellchecker to check English US and French
> myWindow.session.setSpellCheckerLanguages(['en-US', 'fr'])

Currently, ferdi only allow set a single language, I've enabled the spell checker for Spanish and English just editing manually Ferdi/config/settings.json adding the secondary language comma separated:

>   "spellcheckerLanguage": "es-es,en-us",

Tested in MacOS Catalina, works great. I think would be a good option having a multiple selection box into the language settings instead a list.

In any case the manual way also works, have workaround is available on your wiki will be also useful.

Thank you ferdi Dev team 👍

**Comment by ivanddiaz** [comment]
Hello, I just find the automatic detection works like a Charm, no issues there. Sorry for the noise.

**Comment by kris7t** [comment]
Note that spell checking will change substantially in the next release, as we are moving from Electron 8 to Electron 9 and adopting the built-in spell checking backend of Electron 9 instead of the current library. So if you notice any regressions after the upcoming release, feel free to open a new issue!
