### ISSUE TITLE
macOS Big Sur won't open it, and alarming things happen

### ISSUE THREAD

**Issue by thestuntman** [getferdi/ferdi#1084]
The app is blocked on launch because the developer is unverifiable and the app cannot be checked for malware. Of course, you can go into System Preferences and tell it to override the block and open anyway... which I did. But then It says that Ferdi wants to be able to control System Events and access other apps, documents, and alter them.

That may be Apple just alarming folks, but first, I wonder why one would even make a macOS app and then hide their identity from Apple. Wouldn't getting on the approved developer's list be one of the first things you do? To my knowledge, Apple does not require you to be on the MacApp Store to get verified. It's just a matter of registering that you're a legit developer. Again, I'm speculating and maybe you have a reason to go incognito that makes perfect sense... but you've got to see how it would alarm the normal user. If Apple requires money to get on the verified developer list, then put a donation link up. If this app does all it looks like it will do, then I'd be happy to contribute to easing the concerns that are being raised by Apple.

Also, why does a 3rd party communications app need to manipulate other apps, their data, and control my operating system? Again, there's probably some needed call that would speed up the code development by taking a short cut through the system... but again, don't you think this would scare the crap out of people who are about to plug a bunch of sensitive personal passwords into it?

It makes me feel like the dots are connected. That Apple probably wouldn't allow the the control of System Events and that means you have to remain unverified. I'd love to hear more about these issues.

**Comment by vantezzen** [comment]
Thank you for reporting this.

1. "developer is unverifiable", "Wouldn't getting on the approved developer's list be one of the first things you do?"

Actually, we are verified Apple developers! Thanks to our awesome donators over at [OpenCollective](https://opencollective.com/getferdi) we can buy and renew the Apple developer membership for $99 each year.

Now as you noticed, Ferdi still seems to "unverifiable" even though we are verified by Apple. Unfortunately, it looks like we are currently experiencing some problems with our certificate after we last renewed it: Besides showing this message, our current builds also seem to fail notarising. @kytwb do you know what is going on there?

2. "Ferdi wants to be able to control System Events"

Now this might be bit of an unclear message from Apple. We are not controlling other apps, we are not altering other apps and we are not "speeding up the code development by taking a short cut through the system".

The reason for this popup is because we are allowing you to easily start Ferdi at startup from within Ferdis settings.

For this feature we are using the "[auto-launch](https://www.npmjs.com/package/auto-launch)" library. They also have more information on the "System Events" prompt at https://github.com/Teamwork/node-auto-launch#applescript-default. In short: The library uses an AppleScript to add Ferdi to the login items, which makes macOS pop up this message.

We might look into switching to a non-system-event-based alternative in the future, but that isn't a priority at the moment.

3. "It makes me feel like the dots are connected. That Apple probably wouldn't allow the the control of System Events and that means you have to remain unverified."

Now that is not really true, but also not completely false. Using the System Event Method described above doesn't cause any problems with verifying or notarising of applications.
Apple is only checking that we are not actively distributing malware in that step. System Events can be used by many legitimative apps (like ours) so using it doesn't mean that you can't verify your app.

This is however (one of) the reasons, that Ferdi wouldn't get accepted into the official Mac App Store. As the libraries README states: "Note: This is not Mac App Store friendly; if you use it in your app, it will be rejected by the Mac App Store". But as we are not planning on releasing the App Store, this isn't a problem for us right now.

**Comment by thestuntman** [comment]
Great, thanks for clarifying. It's really good to know what's behind all of that. Keep up the good work and I hope things get sorted with Apple soon!

**Comment by Gregor-X** [comment]
So no Ferdi on Big Sur until further notice?
