### ISSUE TITLE
[Question] Is it possible to use Google Tasks with Ferdi Todos?

### ISSUE THREAD

**Issue by amura11** [getferdi/ferdi#1103]
Pretty much exactly what the title asks. I wanted to know if it's possible to use Google Tasks with Ferdi Todos. I know it's possible to change the Todo server but I'm not aware of any API or URL for Google Tasks.

**Comment by haise0** [comment]
I recall being able to use it not too long ago, but when I reinstalled today and went to set up Ferdi again, it was no longer an option. I'm a bit confused. There's an official webapp for it, but I can't find anything about the API or even a URL for it.

**Comment by vantezzen** [comment]
Theoretically, you can add any webpage to Ferdi Todos - we don't use any special APIs for this.

I don't know about Google Tasks as it seems to not have a standalone web page? At least from what I can tell, you can only open a Task-Sidebar from other Google pages (e.g. Gmail)

**Comment by therealgorgan** [comment]
https://tasks.google.com/embed/

**Comment by therealgorgan** [comment]
https://tasks.google.com/embed/?origin=https://calendar.google.com&fullWidth=1

**Comment by gavsiu** [comment]
That link works in a browser but not in Ferdi Todos. It's just blank. I thought maybe it was because I'm signed into Google already in my browser. I tried setting Google Account login link in Ferdi Todos to login first before changing to Tasks, but it gave a "This browser is unsecure" error and won't let me log in. In case this helps.

**Comment by vraravam** [comment]
This is now working as of Ferdi 5.6.0 - closing.
