### ISSUE TITLE
Lunrac.com and Ferdi

### ISSUE THREAD

**Issue by jadmadi** [getferdi/ferdi#1142]
When adding new service, like Whatsapp or FB messenger, Ferdi is communicating with lunrac.com.

Ducking the domain didn't bring positive results on domain reputation

https://duckduckgo.com/?q=ferdi.com++lunrac.com&t=newext&atb=v252-6&ia=web

**Comment by vraravam** [comment]
I have checked in the Ferdi and the recipe codebases - and we do not have this domain name in our code.

Most likely culprit could be either facebook or whatsapp. Can you please open these in a regular browser and check with the same procedure/tools? I'm closing this issue - since its not related to Ferdi per se.
