### ISSUE TITLE
Quick Switch broken

### ISSUE THREAD

**Issue by probablykasper** [getferdi/ferdi#115]
In 5.3.4-beta.6:
- Dark mode does not work and causes text (and icons if they're white) to be invisible
- The input field does not get auto-focused (It does when I launch Ferdi, but after switching to a different service, it stops auto-focusing)
- It's quite tall

![image](https://user-images.githubusercontent.com/11315492/66694635-d21f1980-ecb5-11e9-8a42-5c401ed706f6.png)

- OS: macOS 10.14.6
- Version: 5.3.4-beta.6

**Comment by vantezzen** [comment]
Oh, I'll have to fix the issues with dark mode.

The input field is [an issue I know of](https://github.com/getferdi/ferdi/issues/68#issuecomment-534146281), but unfortunately [it is a known problem in electron](https://github.com/electron/electron/issues/17882): If Ferdi's focus is inside a webview/service, there is no way to gain back focus to Ferdi itself and the search input.

I could add a height limit to the list to avoid having such a long list.

**Comment by probablykasper** [comment]
@vantezzen In the comments of that Electron issue, the first comment mentions finding a workaround, and another comment says `window.blurWebView()` works. Have you tried those?

It could have a height limit, and if exceeded it can scroll. Individual items can also have a much smaller height. When the search field is empty, it could either show no items or the previous 1 or 3 items. Discord's quick switcher might be a good reference:
![image](https://user-images.githubusercontent.com/11315492/66702199-4f25af80-ed05-11e9-8838-38e74d43f3a8.png)

**Comment by vantezzen** [comment]
Yes, I've tried the comment on the issue, but [as already discussed there](https://github.com/electron/electron/issues/17882#issuecomment-486679969), this does not allow to focus on the embedder page.
I also tried Electron's `win.blurWebView()` method (this is [still implemented](https://github.com/getferdi/ferdi/blob/2c86938b03926ac4af547c3a2241d5d0b5c8e257/src/features/quickSwitch/Component.js#L205)), but it looks like it doesn't do what it should? - Unless I implemented it wrong.

I now fixed the DarkMode and height issues. Your other suggestions may require feedback from other users. I don't think we should show no services when no search query is provided - you shouldn't need to search services in order to switch to them.

Please vote:
**What should the QuickSwitch show, when no search query is provided?**
[![](https://api.gh-polls.com/poll/01DQ0A9B6XSV65FF04WTEXCFKX/Show%20services%20in%20default%20order%20(as%20in%20the%20sidebar))](https://api.gh-polls.com/poll/01DQ0A9B6XSV65FF04WTEXCFKX/Show%20services%20in%20default%20order%20(as%20in%20the%20sidebar)/vote)
[![](https://api.gh-polls.com/poll/01DQ0A9B6XSV65FF04WTEXCFKX/Show%20no%20services)](https://api.gh-polls.com/poll/01DQ0A9B6XSV65FF04WTEXCFKX/Show%20no%20services/vote)
[![](https://api.gh-polls.com/poll/01DQ0A9B6XSV65FF04WTEXCFKX/Show%20services%2C%20sorted%20by%20last%20used)](https://api.gh-polls.com/poll/01DQ0A9B6XSV65FF04WTEXCFKX/Show%20services%2C%20sorted%20by%20last%20used/vote)
[![](https://api.gh-polls.com/poll/01DQ0A9B6XSV65FF04WTEXCFKX/Show%20last%203%20services%2C%20then%20show%20a%20list%20with%20all%20services%20in%20the%20default%20order)](https://api.gh-polls.com/poll/01DQ0A9B6XSV65FF04WTEXCFKX/Show%20last%203%20services%2C%20then%20show%20a%20list%20with%20all%20services%20in%20the%20default%20order/vote)

**Comment by vantezzen** [comment]
QuickSwitch will now sort services by last used when no search query is provided.

**Comment by vraravam** [comment]
What is the keyboard shortcut to view the shortcut window?
