### ISSUE TITLE
Ferdi Window Close Bug

### ISSUE THREAD

**Issue by zhr0** [getferdi/ferdi#1182]
**Bug description:**

When i close Ferdi Portable on Windows 10 Pro  on the corner of the Window in the "X" it opens another same Window of Ferdi again and i have two Windows, i can only quit on Menu file. It duplicates the Ferdi program "Window" when the user presses "X" to close. 

**Steps to reproduce:**

Run it on Windows 10 Pro in Portable mode, try to close the Program.

**Expected behavior**

Ferdi closes completely

**Screenshots**

**Environment:**
- Operating System: 
- Windows 10 Pro
- Ferdi Version: 
- Ferdi 5.5.0 Portable
- Server: 

- Debug information:

**Comment by mhatvan** [comment]
v5.5.0 is a really old Ferdi version nowadays, and it seems there are no newer installations available on https://github.com/portapps/ferdi-portable/releases since Jul 25, 2020. We also have no control over how portapps handles the Ferdi installation. 

I would recommend installing an up to date Ferdi version e.g. `.msi` from here instead: https://github.com/getferdi/ferdi/releases/tag/v5.6.4
