### ISSUE TITLE
Why does Ferdi add a new device into Google account?

### ISSUE THREAD

**Issue by lisandrocarmona** [getferdi/ferdi#1208]
I was seeing a strange device into my Google account named as Mac, using Firefox as the browser ID. The IP is also in other country. When I remove the device, my GMail account logouts in Ferdi, when I login again, the new device reappears.
Why is it so?

![image](https://user-images.githubusercontent.com/6163906/108126461-a1f54100-7088-11eb-9fb8-d5d00d32b7d2.png)

**Comment by TheBoroer** [comment]
OS detection is tricky. Could just be a hiccup with google's device detection. About your IP being in another country, it could be that you were using a vpn at some point? Mine shows up at Mac too but the right country/region.

**Comment by lisandrocarmona** [comment]
Sorry for the delay. No, I'm not in a VPN while using Ferdi or when I've registered. Although, I use one occasionally. I understand that app detection would catch Ferdi, not a device search. I was not expecting that behavior.

**Comment by kris7t** [comment]
Ferdi deliberately spoofs the User-Agent for Google, because otherwise Google wouldn't allow Ferdi to log in. See e.g., https://lists.webkit.org/pipermail/webkit-dev/2020-November/031604.html for Google's policy.

For now, a Firefox on Mac User-Agent seems to work fine. But of course, Google could make its "illegitimate" browser detection smarter, and then we'd need other fixes (like emulating some browser features as in https://github.com/getferdi/recipes/pull/308).

**Comment by lisandrocarmona** [comment]
Thank you kris7t, more than explained.
