### ISSUE TITLE
Messenger search not working 

### ISSUE THREAD

**Issue by Mile27ultracoach** [getferdi/ferdi#1210]
**Bug description:**

When using messenger in Ferdi  to search for a contact  - it just spins with no result 

**Steps to reproduce:**

1. Go to '...' messenger 
2. Click on '....' search messenger 
3. Scroll down to '....' blank white spinning circle 
<img width="349" alt="Screen Shot 2021-02-18 at 11 58 13 am" src="https://user-images.githubusercontent.com/79234507/108288414-a7fe3580-71e0-11eb-890c-17068a08cb36.png">

**Expected behavior**

**Screenshots**

**Environment:**

- Operating System: 
- Ferdi Version: 
- Server: 

- Debug information:

**Comment by vraravam** [comment]
@Mile27ultracoach : Could you please be more specific as to which version of Ferdi, which OS, etc that you are using? The issue template prompts for these snippets of information so that we can try to debug and help you. Without it, we won't be able to get much traction.

With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by Mile27ultracoach** [comment]
Think the problem is solved - upgraded to  Big Sur  and seems all working ok now 

Andy 


mile27.com.au 
+61432838241
Training that takes you the extra mile

On 22 May 2021 at 10:00:56 pm, Vijay Raghavan Aravamudhan ***@***.***) wrote:

@Mile27ultracoach : Could you please be more specific as to which version of Ferdi, which OS, etc that you are using? The issue template prompts for these snippets of information so that we can try to debug and help you. Without it, we won't be able to get much traction.

With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available here AND then upgrading the recipes by following the steps outlined here?

If you are on macos or linux, I have shared some newer builds of the latest source code here

**Comment by vraravam** [comment]
Closing the issue since it seems fixed (though I suspect the new install and wiping of the Ferdi profile did the trick). Thanks anyways @Mile27ultracoach .
