### ISSUE TITLE
TickTick not working (Ferdi ToDo's)

### ISSUE THREAD

**Issue by EgoDogg** [getferdi/ferdi#1211]
**Bug description:**
TickTick will not load. It sometimes will load after the initial setup (fresh install), but won't load at any point afterwards. This has been happening for months for me on multiple builds and computers, so figured I would make a ticket. Other To Do lists load fine

**Steps to reproduce:**

1. Go to File > Settings > General Tab
2. Change Todo Server to TickTick (or use the custom web addres)
3. TickTick gets stuck on a loading screen.

**Expected behavior**
TickTick should load. 

**Screenshots**
![image](https://user-images.githubusercontent.com/38112321/108425118-07237080-7208-11eb-83bf-0e1d5aebadd2.png)

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.6 - Nightly 15

- Server: Franz (I think)
- Debug information:

**Comment by andresprone** [comment]
I'm facing the same issue. Already tried clearing cache and reloading Ferdi and ToDos. Did you figure out any way to fix it @EgoDogg ?

**Comment by EgoDogg** [comment]
> I'm facing the same issue. I already tried clearing cache and reloading Ferdi and ToDos. Did you figure out any way to fix it @EgoDogg ?

No luck in fixing it. It's been an issue for months and through various releases, betas, and nightly updates. If there is a manual fix that can be made, it's outside my tech-knowhow.

**Comment by Rixxx-git** [comment]
I have the same issue. It works with the 5.5. version though.

**Comment by onimaca** [comment]
anyone knows how to solve this issue?

**Comment by EgoDogg** [comment]
> anyone knows how to solve this issue?

Not that I know of. For the time being I have Tick Tick as a service, but that's not the most ideal option. I'd like to use the Todos sidebar since everything else works. lol

**Comment by onimaca** [comment]
@vraravam  any clue please?

**Comment by kris7t** [comment]
This seems to be cause by the fact that we don't expose the Chromium version of the User-Agent being used in the todos webview. Exposing the Chromium version causes Google Tasks to reject the login, because Google is hostile to "non-official" (read: not Chrome, Safari, or maybe Firefox) browsers. However, TickTick expects the Chrome version number and fails to load without it.

I'll move the Google login logic over from the service webview to fix fix, and selectively suppress the Chrome version number only for the Google login.

**Comment by EgoDogg** [comment]
Thank you thank you thank you!
