### ISSUE TITLE
Messenger service does not work any longer.

### ISSUE THREAD

**Issue by lruzicka** [getferdi/ferdi#1225]
Today, I got an error message from the Messenger service saying **ERR_NAME_NOT_RESOLVED**. 
In a browser, Messenger works ok. Reloading or deleting and re-adding the service did not help.

Do you know what could go wrong?

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

It would be a good idea to specify more details of your OS version, your Ferdi version, etc so that we can try to help you.

**Comment by vraravam** [comment]
Closing the ticket since there's no response from the OP.
