### ISSUE TITLE
Expose the user-agent in the preferences - so that the user can copy-paste from other references without needing to know javascript and edit the js file

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1239]
**Is your feature request related to a problem? Please describe.**
I see a lot of issues related to user agent string; and references to open up the `user.js` or `webview.js` file. Imo, as the structure of the js object changes over time, the old setting/syntax might not work.

**Describe the solution you'd like**
Instead of the Ferdi user being tech-savvy to edit the js file, can we instead expose this as a setting/preference? Then a wiki page that lists different user agents for different browsers would be enough for lay-people (non-techies) to copy-paste and try out the settings that works for them.

**Describe alternatives you've considered**
I have followed the references to override the user agents in javascript snippets - and have also faced issues where that was malformed due to js syntax issues.

**Additional context**

**Comment by kris7t** [comment]
The main problem is that different services need different User-Agent headers (or other tricks, like https://github.com/getferdi/recipes/pull/308). Afaik there's also at least two ways to override the User-Agent (one for specific requests only, and one for all requests of a service), and there may be situations where different requests for a service need different spoofed User-Agent headers (if we claim to Google that we're Chrome, it'll ran more fingerprinting and conclude that we're not, blocking login, but some other features specifically need a Chrome user agent).  It's kind of an "arms race" between Ferdi and services that want to limit user logins to "official" browsers (maybe they can track users more effectively that way?).

The problem is that we're sorely lacking the manpower to participate in the arms race successfully.

A text field to override the user agent may be a stopgap measure, but it's a poor one (see the need for different headers for different requests as above). Maybe we could have a way to obtain a user-agent header for

* The latest version of Firefox / Chome / Chromium / Edge / Safari, or the actual version of Chromium (with cloaking of browser plugins).
* Running on the actual operating system, or the latest version Ubuntu Linux / macOS / Windows / Android / iOS.

Then the recipes only have to include criteria for these, and they are kept somewhat up to date. Maybe something like https://www.npmjs.com/package/user-agents could help, but without the randomization. Thus the recipe could obtain and apply a user agent header for the specific requests it needs.

Also, we could have a user-level override (textbox, or selection from the criteria above) as a blanket fallback override, should the recipe become out of date.

However, these solutions always remain imperfect. In the limiting case, a service could use some (unpatchable) spectre vulnerability to perform an arbitrary memory read to determine the browser binary being used. Let's hope the arms race never gets to _that_ point.

**Comment by vraravam** [comment]
@kris7t - thanks for the insights. I have only ever encountered the issue with users being asked to navigate to the recipes folder, and edit the `modifyRequestHeaders` method to change the `user-agent` in the `headers` json section. What's a good example of the other style of user-agent-overrides that you can point me to?

IF there's 2 different patterns for the above 2 styles, we could introduce 2 text boxes - one for the global (within the service context), and another for per-request overrides along with other metadata across requests.

I was not thinking of having the actual UA string being hardcoded in the packaged app - its a free-flow text-box which can be entered by the user from searching the web. wdyt?

**Comment by kris7t** [comment]
The problem with the free flowing text box is that the value there inevitably goes out of date, and then the service will stop working. If we ship a hardcoded set of user agent strings (or a user agent generator) that always generates the latest version, we can work around at least that. Having users copy-pase user agent string isn't very scalable, and I think should be reserved for a last resort.

This of course doesn't help if the service figures out how to fingerprint us (like how Skype did, although it wasn't specifically aimed at Ferdi, but any _open-source_ browser including Chromium, but not including Chrome or Edge).

Compare e.g.

https://github.com/getferdi/recipes/blob/master/recipes/msteams/index.js

which uses `overrideUserAgent` to change the user agent in the webview vs

https://github.com/getferdi/recipes/blob/master/recipes/gmail/index.js

which applies it to all possible requests.

Btw, it seems Google gets special handling in

https://github.com/getferdi/ferdi/blob/e3898e2f47db4d056c03708221901d58eb47c8f5/src/models/Service.js#L265-L278

because neither of the APIs provided in `recipe.js` can handle all user agent sniffing it employs.

**Comment by vraravam** [comment]
Closed due to #1535
