### ISSUE TITLE
Is Ferdi still an active project?

### ISSUE THREAD

**Issue by dabesa** [getferdi/ferdi#1256]
Hi folks,

Latest version is 5.5.0 (2020-04-26) and there is a list of open bugs after that release.
Is this project still active?

Thanks

**Comment by kytwb** [comment]
Hi! We have a list of blocking issues to resolve before releasing 5.6.0 (see https://github.com/getferdi/ferdi/issues/1017#issuecomment-775014033). Unfortunately, @vantezzen and I have been very busy and haven't been able to take care of them. Help is welcome, otherwise it will have to wait until one of us can get back to it.

In the meantime, we recommend using one of the beta/nightly releases, or a build from the `develop` branch.
