### ISSUE TITLE
Whatsapp doesn't show new messages badge

### ISSUE THREAD

**Issue by leoheck** [getferdi/ferdi#1301]
Using 5.5.0 and 5.6.0-nightly.15

**Comment by vraravam** [comment]
@leoheck - I had the exact same problem. Please see [this folder](https://github.com/getferdi/recipes/tree/master/recipes/whatsapp) - and edit your local ferdi recipes - the main file that needs editing is: `webview.js` - just copy the full file contents from the above url into your install location. Of course, do this only after quitting Ferdi, and after the edit, restart Ferdi. Please confirm if this works.

**Comment by leoheck** [comment]
Hey, @vraravam See here. You are the man! Thank you. 
![image](https://user-images.githubusercontent.com/1277920/116020057-eae2ec00-a61b-11eb-91c7-5f57786e78bc.png)

**Comment by leoheck** [comment]
Should I close this? What do you recommend?

**Comment by vraravam** [comment]
Thanks for confirming that this works. ❤️

Yes - I would recommend to close this particular issue - since it doesn't really have any other solution (for now). I have created a [feature request](https://github.com/getferdi/ferdi/issues/1302) - which might address the same problem and have suggested a fix. Please upvote if that would meet your criteria. If you have a different solution - please describe.
