### ISSUE TITLE
Ferdi 5.6.0 nightly 57 opens Steam links in popup window instead of default browser

### ISSUE THREAD

**Issue by notNSANE** [getferdi/ferdi#1489]
**Bug description:** When clicking a steam link, they open on a popup instead of default browser. It was working fine on 5.6.0.beta6

**Steps to reproduce:**

1. Add Steam
2. Click on a link

**Expected behavior**: Link opens in default browser.

**Screenshots**

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.6.0 nightly 57
- Server: Ferdi

- Debug information:

**Comment by vraravam** [comment]
This is due to the behavior of the service itself (which is outside of Ferdi's control).

For whatsapp, gmail and certain other services, the links are rendered with `target='_blank'` - and these open correctly in the external browser (as of the latest code). For Steam, these links are rendered with `target='_top'` - which causes them to open within Ferdi. I would not be so sure to term this as a bug in Ferdi. Its more of an enhancement, wdyt @kris7t ?

**Comment by kris7t** [comment]
We should somehow add an API for recipes to change where links are opened. Then the `steam` recipe could simply make every `_top` link open in the external browser.

This would also be useful in the reverse direction, e.g., to force Slack attachment downloads open _inside_ Ferdi (so that you don't have to log in to Slack in the external browser). The `skype` recipe does something similar in its `webview.js`, albeit with an event listener hack.

Actually, maybe we could repurpose the even listener hack from `skype` for `steam` to force an external browser opening.

**Comment by vraravam** [comment]
thanks for the pointer @kris7t  - let me try to research if I can get that working.

**Comment by vraravam** [comment]
@notNSANE - could you please take the latest version of the recipe and try once more and check if this behavior is what you expected? This fix has been made specific to steam and not in a generic manner.

**Comment by notNSANE** [comment]
how do I know I have the latest version of the recipe? Or where do I get it? Sorry, kind of a noob at these processes.

**Comment by vraravam** [comment]
@notNSANE - could you please try with the steps outlined [here](sudo xcodebuild -license accept)?
