### ISSUE TITLE
feature request : Export/Import local account settings

### ISSUE THREAD

**Issue by AkechiShiro** [getferdi/ferdi#1515]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use Ferdi without an account but be able to export my account to other devices, I'm not sure that it is technically feasible right now, moving some Ferdi local files from one computer to the other, it makes a lot of assumptions.

**Describe the solution you'd like**
Import/Export settings account (not running on any server).

**Describe alternatives you've considered**
Import/Export all Ferdi settings for instance, or copy everything in /home/username/.config/Ferdi (but that's in my honest opinion probably a very bad idea for reasons which I'm not aware).

**Additional context**
It could be useful, to implement this feature which is already in most software (for exporting/importing settings in like JetBrains IntelliJ's IDEs etc.).

**Comment by vraravam** [comment]
This is a good idea. I will see if I can dig some more into the code around this to make it happen.

**Comment by vraravam** [comment]
@AkechiShiro - Since the time that you had reported this ticket, I have exposed a new menu `Help > Import/Export Configuration Data`, which will open a browser window to the server that you are currently using. From here, you should be able to import/export your conifiguration data. If this doesn't appear in the version of Ferdi that you are currently using, please switch to the latest nightlies where this is present.

For eg, I am using Ferdi without a server (ie with an internal server), and so using that menu, this is the website that opens up - and it clearly shows the links to the page(s) where these operations can be carried out:
<img width="1720" alt="Screenshot 2021-08-29 at 6 42 30 PM" src="https://user-images.githubusercontent.com/69629/131251547-df0fac36-c156-40a4-825c-c2d20e347b5d.png">
