### ISSUE TITLE
Question about Ferdi not remembering SSO state (and also reload services notice)

### ISSUE THREAD

**Issue by g4z** [getferdi/ferdi#1573]
every time i open Ferdi, i have to...

* reload services (because my services have been updated -- according to the blue bottom bar)
* go through the Google SSO approval process for Slack

![Screenshot from 2021-06-28 11-10-14](https://user-images.githubusercontent.com/16230360/123611547-00ce8200-d802-11eb-910c-e63d072cb7cd.png)

i see other reports about "services being updated", but in my case.. once i reload the blue reminder bar goes away until next time i startup Ferdi.

any hints on why it's not "remembering" my Google SSO state for Slack?

**Comment by vraravam** [comment]
@g4z - could you please specify what version of Ferdi (and of the slack recipe) that you are using?

I am using the latest nightly from [here](http://github.com/vraravam/nightlies/releases) - specifically v68 - please try with this and report back whether this is still an issue.

**Comment by g4z** [comment]
sorry, i forgot to state the version: 5.6.0-nightly.57
i will try with latest 5.6.0-nightly.68 and update this ticket later
thanks

**Comment by g4z** [comment]
same behaivour so far with 5.6.0-nightly.68

- logout of slack (within Ferdi) and exit Ferdi
- start Ferdi
- shows slack login screen
- (if i wait a few seconds, blue bottom bar "reload services" appears)
- (if i do reload services, blue bar disappears)
- click login with google
- go through the Google SSO process (as in my original screenshot)

i will try to debug a bit by watching the ~/.config/Ferdi directory for changes.

i'll have to do it later though as i have to work right now.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

**Comment by g4z** [comment]
to clarify, there seems to be 2 issues here:

1) everytime i load ferdi, it asks me to reload it because "services have been updated"
2) each time i login to Slack (daily, as per company policy), i have to complete the entire Google SSO process

attached is an inotify log of file accesses in ~/.config/Ferdi (no idea if this is useful!)

[ferdi-inotify.log](https://github.com/getferdi/ferdi/files/6762221/ferdi-inotify.log)

**Comment by vraravam** [comment]
@g4z : Please specify the following info:
1. Are you using Ferdi with or without a server? If yes, which sever?
2. Have you configured Slack as a custom service or did you use the in-built 'Slack' service?
3. In the Slack service settings screen, if you scroll all the way to the bottom, there will be a version info displayed - could you pls post that?
4. Since we are now on nightly v75, could you please upgrade to this version before trying any of the above?

Please respond back with all the above - and I will try to help.

I am using the latest nightly, Slack (with Google-based SSO) - and the slack being the normal (unmodified) service that is present. I don't see any of the above problems that you describe.

The only other thing I can think of: If you are using Ferdi wth an account - then please wipe out the "recipes" folder that is present inside your Ferdi profile folder - and restart Ferdi. Since you are using it with a server, all the registered services should be re-populated upon the restart, and we will ensure that you are on the latest versions of the service recipes.

**Comment by vraravam** [comment]
I re-read your previous comments: Can you please try quitting Ferdi without logging out of Slack? Does that change the behavior?

Since you are using SSO-based login for slack, if your company's SSO configuration expires the login after 24 hrs, then that is probably forcing you to re-login via Google - which is nothing that Ferdi can help with.

**Comment by vraravam** [comment]
The blue bottom "reload of services" is, as you said: a different problem. I suspect that your on-disk files are not being overwritten correctly by the new versions of the recipes - which is why I asked for the version of the service recipe in my above comment.

**Comment by g4z** [comment]
i updated to nightly 75. the same two issues exist based on my quick test.

- logged out of slack
- quit ferdi
- updated Ferdi to nightly 75 (.deb package)
- open ferdi
- few seconds later, the blue bar suggests reloading
- login to Slack using Google, go through SSO setup

answers to you questions:

1) Without a server (as far as i know!). i just installed the Ferdi app from https://github.com/getferdi
2) I'm using the Slack build-in service
3) Recipt version: 1.0.15
4) done

"If you are using Ferdi wth an account"

i don't have a Ferdi account.

"Can you please try quitting Ferdi without logging out of Slack? Does that change the behavior?"

when i quit Ferdi whilst still logged into Slack, on the next Ferdi start up, i am logged into Slack directly (no SSO stuff)
all versions of Ferdi i have tried have worked like this. i only see the Google SSO setup screen after i have either manually logged out or i am auto-logged out due to company policy.

yes, perhaps this is related to my company policy!

neither of these issues are "critical" imho... just minor inconvienences. i'm happy to live with them. they're not worth spending much time on! thanks for the help though :)

**Comment by vraravam** [comment]
thanks @g4z for responding quickly!

As I mentioned, this looks like an SSO-behavior (each time you log out of slack, then SSO auth token gets marked as expired) - this is not something we have control over (from Ferdi).

The blue reloading bar is showing up since your service recipe is not being overwritten. I can see that the version of slack is `1.0.16` from [here](https://github.com/getferdi/recipes/blob/master/recipes/slack/package.json#L4).

As I requested, please delete the `recipes` folder from within your Ferdi profile folder, and restart Ferdi - this should resurrect with the newest version of the recipe

**Comment by g4z** [comment]
ok... "blue bar" no longer appears :)

- shutdown ferdi
- deleted ~/.config/Ferdi/recipes
- started up Ferdi

slack service shows version 1.0.16 and i see no more "reload services" blue bar.

thanks.

**Comment by vraravam** [comment]
Thanks @g4z - so, it was some issue during update of recipes. Closing this ticket.
