### ISSUE TITLE
Messenger: Not able to login

### ISSUE THREAD

**Issue by raguay** [getferdi/ferdi#1578]
**Bug description:**

My Messenger service quit going to the login and saving my login. Now, I removed it and re-added the service and you can still not log in. I turned off Dark mode and the screen still doesn't show a login prompt. I tried it on Stack as well, and it has quit working there. Therefore, it is some change in their service.

**Steps to reproduce:**

1. Create a Messenger service
2. Click on it's icon to the left.
3. You will see a screen about Messenger, but there is no where to login.

**Expected behavior**

The ability to log into the service.
int
**Screenshots**

I live in Thailand, so the screen is coming up in Thai.
![8154817F-014A-4488-ADE0-F03BAE59AAC2](https://user-images.githubusercontent.com/2487495/123903736-7882e500-d999-11eb-8dc1-cd867858e8c5.png)

**Environment:**

- Operating System:  macOS Big Sur 11.4 on MacBook Pro M1
- Ferdi Version:  Version: 5.6.0-nightly.57
Electron: 13.1.0
Chrome: 91.0.4472.77
Node.js: 14.16.0
Platform: macOS Big Sur
Arch: arm64
Build date: Fri Jun 04 2021 05:43:51 GMT+0700 (Indochina Time)
Git SHA: 22708d9b
Git branch: HEAD
- Server: 
Not using an account

- Debug information:

**Comment by vraravam** [comment]
@raguay - could you please post screenshots with English - so that I can try to help?

Without understanding your screenshot, let me try to propose some steps:
1) Please upgrade to the latest nightly found [here](http://github.com/vraravam/nightlies/releases) - I think its at v68 as of right now. Please try this and get back whether this is still an issue
2) Please use the context menu to navigate to the home page of the service. Does this bring you to the login screen?
3) In your page that you show, do you not see anything related to "Login here"? If so, this is a UX design that the website authors have decided. Ferdi cannot do anything for this case

Please do all the above in sequence, and then get back with a new screenshot - I will try to help asap.

**Comment by raguay** [comment]
Okay. The lastest is working after it said it needed to update the service. Yes, the login on the left side was totally missing. Even the HTML wasn't there and the context menu was missing. If Ferdi doesn't do scraping on the page, then it must have been a glitch in the Messenger service. Not sure. But, it is okay now.
