### ISSUE TITLE
Dark Theme not working

### ISSUE THREAD

**Issue by leoheck** [getferdi/ferdi#1604]
Google services as Chat and Calendar do not set the theme to dark. I recall in the past this was working. 

This flag is set but it does nothing. 
![image](https://user-images.githubusercontent.com/1277920/124396824-56170180-dce2-11eb-8fe9-ffc3e174899e.png)

I am using 

![image](https://user-images.githubusercontent.com/1277920/124396770-fcaed280-dce1-11eb-9432-a33bce825a4b.png)

[Off-topic] could we have a way to copy this Ferdi info as a text? I cannot select from this window. Other software like Kicad has a button to copy this as it is. But allowing users to select text is even better.

**Comment by vraravam** [comment]
@leoheck - I just approved a PR in the recipes repo (linked above). Please wait for approx 20 hrs for the next nightly which will automatically pull these fixes. else, you can manually replace the contents of the `webview.js` from the above repo into your installed profile folder location.

**Comment by vraravam** [comment]
I have verified that this works locally in a packaged app.

**Comment by leoheck** [comment]
Using this latest version. Still the same. Google Chat and Google Calendars are not using dark themes.
![image](https://user-images.githubusercontent.com/1277920/125013203-c6ef4e00-e041-11eb-9e52-03b02c7f2ffd.png)

![image](https://user-images.githubusercontent.com/1277920/125013253-e25a5900-e041-11eb-9a5e-88be29f58d93.png)
![image](https://user-images.githubusercontent.com/1277920/125013270-ea19fd80-e041-11eb-982a-881d393c1644.png)
![image](https://user-images.githubusercontent.com/1277920/125013310-fdc56400-e041-11eb-9e99-9c8cb91d5f5f.png)

Am I missing something? Should I do something different? Do you have any tip or workaround that I can test to activate dark themes on these 2 services?

**Comment by vraravam** [comment]
@leoheck : I myself discovered this from another user:
1. In the top view menu `View > Toggle Dark Mode` is present. This is the global one that Electron controls for turning on/off dark mode. For Ferdi to even do anything, this needs to be "on".
2. Within Ferdi's preferences (outside of any service pref), inside `Appearance`, there is a setting for "Enable universal dark mode" - this needs to be turned on. This will try to impose a universal dark mode for all services. Sometimes (as in the case of gChat) this turns messy.
3. Within each service preference, one can turn on/off the dark mode - specific to _that_ service.

Now, since **gChat does not natively support dark mode**, the messiness comes forth even if you follow all the above steps and turn on dark mode in Ferdi. One way to see how to fix this is by seeing how midnight lizard does the overlay. i tried several dark overlays, [midnight lizard](https://github.com/Midnight-Lizard/Midnight-Lizard) seems to be the one that works well for google chat. YMMV.

For more reading, see [here](https://gadgetstouse.com/blog/2020/11/03/how-to-use-dark-mode-in-google-chat-on-android-ios-desktop/)

**Comment by leoheck** [comment]
Hmm, tested #1 here, #2 and #3 were already set. Google Calendar did not change. Google Chat is messy as you mentioned. I thought I saw these 2 services 2 dark in an old version of Ferdi.

**Comment by vraravam** [comment]
@leoheck - please see the release notes of the nightly that I just released: https://github.com/getferdi/nightlies/releases/tag/v5.6.0-nightly.80 - and please confirm if this fixes the dark mode issue for gCalendar.

**Comment by leoheck** [comment]
![image](https://user-images.githubusercontent.com/1277920/125104873-3a31a800-e0b4-11eb-8fdd-beb8743b692a.png)
It didn't work on Gcal. Anything special that I have to do?
1) it was active (toggle it on/off/on once to make sure it was ok)
3) it was active (toggle it on/off/on once to make sure it was ok) 
2) was not active (Settgins > Apparence > Global Dark Mode), didn't change GCal even after restarting Ferdi a couple of times.

**Comment by leoheck** [comment]
I am in Brazil. Are you in India or in another country far from me?
Maybe we have different versions of the Calendar since you are not experiencing the same issue regarding the mobile version being displayed by default. 
This is just an idea that came now but since I am not aware of web technologies I might be wrong.

**Comment by vraravam** [comment]
@leoheck - yes - Im in India.

The last thing that I would suggest you try is to delete the ferdi profile folder, (or at least all the cache folders) and restart Ferdi. In at least one other instance (in the past 24 hrs), this has proved to fix the problem.
