### ISSUE TITLE
Remove uses of the `@electron/remote` and switch on Chromium Sandboxing

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1635]
(Taken from the description of #1456 - capturing as a separate card so that we don't lose track of this important thought process)

> As a next step, we should try to [follow Electron best practices](https://nornagon.medium.com/electrons-remote-module-considered-harmful-70d69500f31) and remove uses of the `@electron/remote` module from the recipes and switch on [Chromium sandboxing](https://www.electronjs.org/docs/tutorial/sandbox), but that will be even more involved. An additional valuable resource is the [Electron security guide](https://www.electronjs.org/docs/tutorial/security).

**Comment by vraravam** [comment]
Just created 2 PRs to finish these cleanups:
https://github.com/getferdi/recipes/pull/674
https://github.com/getferdi/ferdi/pull/1869 - this one needs to go in first.

**Comment by vraravam** [comment]
Closing this since the 2 PRs have been merged.

**Comment by mhatvan** [comment]
Issue is reopened because we removed deprecated remote module of electron in favor of `@electron/remote` BUT issue is about removing `@electron/remote` and enabling sandboxing to follow electron security best practices.

**Comment by vraravam** [comment]
@mhatvan - Based on the latest PRs, wouldn't the dependency on `@electron/remote` also be called as "removed"?

I do agree that the enabling of sandboxing is still an outstanding task to be completed.

**Comment by mhatvan** [comment]
Removed for recipes yes, but not all occurrences which would be the best practice according to: https://nornagon.medium.com/electrons-remote-module-considered-harmful-70d69500f31

**Comment by vraravam** [comment]
Looks like this is the only outstanding reference? https://github.com/getferdi/ferdi/blob/develop/src/api/server/ServerApi.js#L14

**Comment by kris7t** [comment]
There seem to be plenty of references to `@electron/remote`:

```
package.json
66:    "@electron/remote": "1.2.1",

package-lock.json
2393:    "@electron/remote": {
2395:      "resolved": "https://registry.npmjs.org/@electron/remote/-/remote-1.2.1.tgz",

src/stores/SettingsStore.js
2:import { getCurrentWindow } from '@electron/remote';

src/stores/UIStore.ts
3:import { nativeTheme, systemPreferences } from '@electron/remote';

src/stores/UserStore.js
5:import { session } from '@electron/remote';

src/models/Service.js
3:import { webContents } from '@electron/remote';

src/lib/TouchBar.js
2:import { TouchBar, getCurrentWindow } from '@electron/remote';

src/features/workspaces/components/WorkspaceDrawerItem.js
1:import { Menu, getCurrentWindow } from '@electron/remote';

src/index.js
11:require('@electron/remote/main').initialize();

src/stores/AppStore.js
9:} from '@electron/remote';

src/lib/Menu.js
2:import { app, Menu, dialog, systemPreferences } from '@electron/remote';

src/features/serviceProxy/index.js
2:import { session } from '@electron/remote';

src/webview/sessionHandler.ts
1:import { getCurrentWebContents } from '@electron/remote';

src/webview/spellchecker.ts
1:import { getCurrentWebContents } from '@electron/remote';

src/webview/find.js
4:// Shim to expose webContents functionality to electron-find without @electron/remote

src/webview/contextMenuBuilder.js
11:import { Menu, MenuItem } from '@electron/remote';

src/webview/contextMenu.js
1:import { getCurrentWebContents } from '@electron/remote';

src/webview/lib/RecipeWebview.js
2:import { BrowserWindow } from '@electron/remote';

src/features/quickSwitch/Component.js
2:import { getCurrentWindow } from '@electron/remote';

src/api/server/LocalApi.ts
2:import { session } from '@electron/remote';

src/api/server/ServerApi.js
14:import { require as remoteRequire } from '@electron/remote';

src/components/auth/Locked.js
1:import { systemPreferences } from '@electron/remote';

src/components/settings/supportFerdi/SupportFerdiDashboard.js
3:import { BrowserWindow } from '@electron/remote';

src/components/settings/settings/EditSettingsForm.js
1:import { systemPreferences } from '@electron/remote';

src/components/services/tabs/TabItem.js
1:import { Menu, dialog, app, getCurrentWindow } from '@electron/remote';
```

In general, we'd need to remove all references from `src/webview` so that we can turn on sandboxing for the service webviews. This means all communication from the recipes to Ferdi should go through custom electron IPC messages.

As an example, look at `src/webview/spellchecker.ts`. Here, the code running in the service webview isolated world is setting up the spell checker via `getCurrentWebContents` in the remote module. This mean the remote module creates a proxy object from the `WebContents` and the `Session` for the service webview inside the service webview, which communicates with the electron main process, where the actual `WebContents` and `Session` objects resides. This is 1. somewhat insecure 2. massively slow.

To fix this, we'd need to add handling for a custom IPC message in the electron main process, where we do the same setup, but without the remote module overhead. Note that preloaded scripts in the isolated world can send IPC messages to the main process even if sandboxing is enabled (otherwise, sandboxed webviews couldn't interact with rest of the app at all).

Removing references to the remote module from stuff running in the top-level Ferdi renderer process (i.e., the `BrowserWindow`) is also possible this way, but less critical. Current, Ferdi is set up so that all the application-level logic is in the top-level renderer process, not the main process. Compare `src/index.js`, which runs in the main process and handles IPC messages, vs `src/app.js`, which runs in the top-level renderer process. All the models, stores, reactions, etc. are set up in the `src/app.js` and it is fully trusted (i.e., a part of Ferdi). So there's little point in sandboxing it (it can basically do anything, since it dictates the whole application logic). Instead, our focus should be on the service webviews, which run untrusted code (the scripts in the service webpage).

(I'm using _top-level_ renderer in a very loose sense here. Actually, chromium renderer processes are not hierarchical, and the only communicate via IPC with the main process, not directly with each other. But the `Webview` objects for the services are instantiated in the document running in top-level `BrowserWindow`, so it makes some sense to call its renderer top-level. Certainly, if the top-level document removes a `WebView`, the corresponding renderer exits.)

**Comment by vraravam** [comment]
Thanks for the great writeup @kris7t. To be more clearer, what are the occurrences that we will need to replace with ipc messages? (I understand the `spellchecker` is a good example, but "remove from `src/webview` seems to be too broad?)

**Comment by kris7t** [comment]
At the very least these:

```
src/webview/sessionHandler.ts
1:import { getCurrentWebContents } from '@electron/remote';

src/webview/spellchecker.ts
1:import { getCurrentWebContents } from '@electron/remote';

src/webview/contextMenuBuilder.js
11:import { Menu, MenuItem } from '@electron/remote';

src/webview/contextMenu.js
1:import { getCurrentWebContents } from '@electron/remote';

src/webview/lib/RecipeWebview.js
2:import { BrowserWindow } from '@electron/remote';
```

plus there might be other libraries that rely on remote proxies internally, I'm not sure. `src/webview/find.js` illustrates the approach we need: add IPC message handler to the main process, then call them from the webview.
