### ISSUE TITLE
How Feasible is Deno Integration and/or Other Changes? 

### ISSUE THREAD

**Issue by Librechain** [getferdi/ferdi#1674]
There are certain changes that I want to make to Ferdi (for a forked version I'm creating for separate, private purposes).

However, if any of the changes that I make are of use to the community - I'd be more than happy to contribute that code to the upstream project (Ferdi) so that the primary maintainers can adjudicate whether they feel these changes are worthy of being included in the main project or not. 

### Hoping For a Bit of Guidance on How / Where Changes Could be Made to Improve Ferdi 

Ferdi is already great. By no means is this suggesting that the app is in need of a ton of improvements.

But given that this is an open source project, there are probably certain things on the 'wishlist' that exist slightly beyond the constraints of currently available resources (at the time of writing). Whatever those things are, those are the aspects of Ferdi I'd like to deploy resources to seeing if I can change substantively. 

Specifically, I was hoping to make augmentations that would: 

- Allow Ferdi to use a different webview (not sure if Deno is mature enough for this) 
- Allow for the replacement / swapout of Electron entirely (again, not sure how feasible that this is) 
- Improve the way that the app interacts with the overall operating system (if there are any changes that can be made here) 
- 'Harden' the network aspects of the app (if possible); was considering ideas such as a possible 'Tor' mode (not sure how feasible this is; forgive me if I'm speaking entirely out of ignorance) 

### Ultimate Idea 

I have a suite of open source tools that I provide for subscribers. An app like Ferdi stands out as something that would be perfect for those that are looking to have a 'desktop app' that essentially allows them to securely log in to access these tools without necessarily having to go through a browser. 

Many of the tools are PWAs, but there are some that also utilize Electron as well (I'm not well-versed in how non-Electron apps are able to communicate with Electron-based ones). 

### More Background Information 

I like this project a lot and expect to have a significant amount of resource to deploy toward my project in the near future. Since Ferdi is a great community with hard-working, diligent individuals that have selflessly given up countless hours to make this project come true, I'd like to deploy some of my capital & resources to build up this project in any manner possible. 

If this is not desired, I will leave everyone alone. Only looking to contribute in some way since I'm in the rare position to maybe be of assistance for projects like this that absolutely deserve everything and some.

**Comment by kris7t** [comment]
> Allow Ferdi to use a different webview (not sure if Deno is mature enough for this)

> Allow for the replacement / swapout of Electron entirely (again, not sure how feasible that this is)

This is nearly impossible. Ferdi runs as an electron app, so it's based on the v8 javascript runtime and chromium as a renderer. It uses a bunch of electron-specific APIs, which would have to be rewritten. This basically would entail a rewrite from scratch, since even the most basic ways of how service data (cookies, localStorage, etc.) are saved is chromium-specific (persistent partitions).

Specifically regarding the webview replacement, you _might_ be able to do that by positioning your webview as a window over Ferdi's normal webview, essentially how embedding other windows in an application was done in X11 before XEmbed. But that would obviously be platform-specific (how to make a window borderless and skip the taskbar, how to position it over Ferdi, etc.) and act a bit strange (e.g., you wouldn't be able to open Ferdi's settings dialog above it).

> Improve the way that the app interacts with the overall operating system (if there are any changes that can be made here)

This is feasible, as long as the OS-specific APIs have nodejs bindings, or if you are able to create such bindings. For some cases, even pure javascript solutions without any native code (e.g., talking to DBus under Linux) should be feasible.

> 'Harden' the network aspects of the app (if possible); was considering ideas such as a possible 'Tor' mode (not sure how feasible this is; forgive me if I'm speaking entirely out of ignorance)

There was some work to add Proxy support, see e.g. https://github.com/getferdi/ferdi/pull/783. Tor mode would just be a SOCKS proxy (and maybe a Tor daemon in the background). However, proxy support for Electron apps seems to be tricky.

> I have a suite of open source tools that I provide for subscribers. An app like Ferdi stands out as something that would be perfect for those that are looking to have a 'desktop app' that essentially allows them to securely log in to access these tools without necessarily having to go through a browser.

This is most likely possible, but not directly supported. You could fork the Ferdi repo, swap out the branding, run your own Ferdi server (to save user accounts), change what services are set up by default for new accounts (so users start with the expected tools), and maybe expose some API to services that identifies the currently logged in user. Rebasing upon upstream Ferdi at every release might turn out to be a pain point, though.

However, this is most certainly _going through a browser_, albeit specific browser instance (of chromium).

> Many of the tools are PWAs, but there are some that also utilize Electron as well (I'm not well-versed in how non-Electron apps are able to communicate with Electron-based ones).

Electron-based apps are a problem, because an electron app is split into a main process (on nodejs, with full filesystem access and other privileges) and some renderer processes (usually one for each webview, sandboxed), which are in turn split into an isolated world (which can communicate with the main process over message queues) and a main world (with a much more limited communication and tighter sandbox).

Out of this, Ferdi runs services in the main world of the renderer process corresponding to the service's webview. Recipes can execute code in the isolated world, so it would be possible to ship the sandboxed part of an electron app split between a recipe (isolated world stuff, cannot be updated automatically) and a webpage (main world stuff, automatic updated possible). However, any main process stuff would need to be added to Ferdi's code (or a fork thereof) directly and you'd have to make sure the names of the IPC messages don't clash with Ferdi's own, internal messages. Any such 'embedded' electron apps would run with full privileges (due to their main process code) and thus could be in no way isolated from each other. So only attempt this with electron apps that you fully trust -- in particular, any 'embedded' apps would be able to read each others' secrets!

---

Nevertheless, your contributions, if useful for the original purpose of Ferdi, would most certainly be welcome here. Feel free to open any PRs!

**Comment by vraravam** [comment]
@Librechain - I'm closing this ticket - since its not something that we can entertain - as @kris7t said, the dependency on electron and its APIs are too much for this to be a viable direction for exploration.
