### ISSUE TITLE
No sound notification with sound activated ?

### ISSUE THREAD

**Issue by b0san** [getferdi/ferdi#1691]
**Is your feature request related to a problem? Please describe.**
When I disable audio notifications, then I can't listen to the audio messages. 
But when I activate the audio notifications, then each time I receive a message both my cell and my computer notify me. 

**Describe the solution you'd like**
I'd like to be able to choose to disable audio notifications but still listen to audio messages through Ferdi.

**Describe alternatives you've considered**
Actually I have to choose either to turn off the sound of my cellphone (but I might miss a phonecall) or to disable all audio notifications in Ferdi and switch to the cell phone if I receive an audio message...

**Additional context**
Thank you all for the great job!

**Comment by rodreras** [comment]
Another thing that I realized is that we can't disable popup notifications and keep the sound when we receive a message. I think this also suits to the problem reported by @b0san .

If it's possible, please, explain me how to do it. Since I've been using Ferdi for a couple days, I might have not found how to disable this.
