### ISSUE TITLE
Ferdi Snap app

### ISSUE THREAD

**Issue by ayxos** [getferdi/ferdi#1749]
I am a ubuntu user and I love Ferdi, at the moment I check the github package checking if I have the latest version.
Using Snaps would automatically keep the app updated.

It would be nice to have a snap package published on snapcraft.

It would have multiple benefits.

User point of view:

Compatibility with multiple Linux systems
Auto update
Improved security through sandboxing
Access to /dev by using permission, no need to run as root anymore
Developer/publisher point of view:

Visibility
Free
Easy to publish
Version management
Usage metrics

https://snapcraft.io/

**Comment by mhatvan** [comment]
Hey @ayxos, thank you for opening this issue! 

As an Ubuntu user myself, I would love to see this implemented too ;)

I played around with snaps in the past out of interest, so will pick this up and see what I can do!

**Comment by mhatvan** [comment]
Newest nightly can be accessed now on Snapcraft: https://snapcraft.io/ferdi :tada: 

We will still need to setup automatic deployment of new versions through GitHub and add stable and beta release channels.

**Comment by vraravam** [comment]
Unfortunately, we had to revert this PR #1756 since there were additional changes required for the publishing step.

@mhatvan - If you can maybe disable the publishing to the snapstore based (or) add the additional configurations in the build scripts and the GH actions scripts (to install the required apt package) to publish: https://www.electron.build/configuration/publish - then we can go forward with this.

**Comment by mhatvan** [comment]
Snaps are now auto-published and regularly updated in the snapstore for stable, beta and nightly releases!
