### ISSUE TITLE
Tray icon always has entry called "Show Ferdi" no matter if main window is active or hidden

### ISSUE THREAD

**Issue by mhatvan** [getferdi/ferdi#1955]
**Bug description:**
I would expect that the tray icon has text for Hide/Show Ferdi, synced based on the state of the main window.

**Steps to reproduce:**

1. Click on "Show Ferdi"
2. Ferdi window is active 
3. Tray entry still is "Show Ferdi" with window active

**Expected behavior**
3. Expect tray entry to say "Hide Ferdi" instead of "Show Ferdi" to minimize it

**Environment:**

- Operating System: Ubuntu 21.04
- Ferdi Version: 5.6.3-nightly.3
- Server: Ferdi

**Comment by kris7t** [comment]
I hardly think this is a _good first issue_, since it's most likely related to how chromium creates tray icons in Linux. In short: it's a mess.

The only way to _properly_ fix this (i.e., make it work on most desktop environments) is to completely ignore chromium's tray icon functionality and roll our own from javascript by talking to the desktop environment over DBus. The same goes for the icon disappearing / appearing twice under some situtations.

I started trying to write a dbus-based implementation a long time ago (hence our dependency on `dbus-next`), but I haven't been able to complete it yet.

**Comment by mhatvan** [comment]
We seem to have the toggle functionality down for the other tray entries like: enable/disable notifications, so I assumed we could do the same thing for Show/Hide Ferdi. Haven't looked at the code part though.

**Comment by kris7t** [comment]
Ah, yeah, maybe modifying the menu (as opposed to the icon itself) is less problematic. 🤞

**Comment by vraravam** [comment]
Fixed via #2234
