### ISSUE TITLE
Cant re-arrange services on UI

### ISSUE THREAD

**Issue by propiro** [getferdi/ferdi#1982]
(Previous issue https://github.com/getferdi/ferdi/issues/1895#issuecomment-920308071 was closed because i couldnt respond in time, so here is new one, with answers about OS, Ferdi Version and developer console )

Hello,
Yes, of course this is still issue, i just dont have time to chime in very often.
``` Also, please post the version of Ferdi, your OS, etc ​```

Windows 10
Version	10.0.19042 Build 19042

Ferdi version 5.6.0 (doesnt matter, happens on 5.5. as well)
Electron 13.1.7
Chrome 91.0.4472

Whats weird, it doesnt happen if im not connected to ferdi services,  i've run ferdi without internet connection, and icons were arranged correctly, but as soon as i've plugged network cable and ferdi cot internet connection, they re-arranged incorrectly.

As for developer console, its spammed with:

https://i.imgur.com/2TPQvhG.jpg

Best Regards,
A

**Comment by vraravam** [comment]
If this is working without an internet connection, but fails with the connection, then I suspect that this is more of a bug in the ferdi-server rather than ferdi itself. Could you please close this bug, and create one [here](https://github.com/getferdi/server/issues/new)?

Also, the ferdi server is only used to store:
1. the services you have signed up for, their order & preferences
2. the workspaces & their order & the services related to the workspaces

The only use of this, is to be able to switch machines and get these prefs transferred to the new machine. If you use Ferdi only in a single machine most of the time, I would suggest that you move to using Ferdi without a server. You can export your current prefs before this switch, and import that configuration back in so that your transition is seamless.

**Comment by propiro** [comment]
Hello, thanks for answer.
I never saw a need for ferdi account, and it felt strange it required me to make one - I only did it, because every restart, Ferdi keep losing all my services (I rarely restart my work pc, but setting up 10 services every month or so was annoying) - and stopped when I've set up an account. 
Could you please point me to exact option for exporting preferences? I have my account exported as backup, but since I'm going to not use it, I assume preference export is different thing from account export.

All the best,
A.

**Comment by vraravam** [comment]
<img width="383" alt="Screenshot 2021-09-24 at 4 51 25 AM" src="https://user-images.githubusercontent.com/69629/134596286-8d476f9a-6659-4b9a-bc52-d3aa9d4f2c7f.png">

and follow the instructions there. (It might be the same as what you meant by "account export"). Once done, you can use the "Logout" link in the lower left of the Settings/Preferences window/screen. Then choose "Use Ferdi without a login" and import the exported `ferdi.data` file.

**Comment by propiro** [comment]
![image](https://user-images.githubusercontent.com/21067369/134596584-203b32ae-ec4f-4e26-b328-9ee4e3f16e3c.png)
sadly, i have no such option

**Comment by vraravam** [comment]
Since you are using it with a server, you can go to https://api.getferdi.com/user/login and export your data.

Also - please upgrade to version 5.6.2 of Ferdi. It's very hard to find and fix issues in older versions of Ferdi - we are all voluntary contributors.

**Comment by propiro** [comment]
``` Since you are using it with a server, you can go to https://api.getferdi.com/user/login and export your data. ```
thats what i did, it gave account data - even if its actual preferences, how do i import it to ferdi (...i dont want to login to import data that already is when im logged to log out and dont have the data, because it was imported for login not for non-login ferdi usage)
So i cant export it, and im at risk of losing settings if "something" happens.

I can confirm that on newest version i cant re-arrange services as well, so its correctly assumed an server issue.

**Comment by vraravam** [comment]
1. If you simply logout of Ferdi-server (without deleting the online account in getferdi.com), then you can always go back to it.
2. I dont know why the `Help` menu is not showing up for you, but, after you start ferdi, you can visit [this local site](http://localhost:45569/) - and follow the links to import your previously exported data.

**Comment by vraravam** [comment]
@propiro - I'm closing this ticket since there's a new ticket in the appropriate `server` repository. Please continue the conversation here in case you need help with the import/export of settings. Or else, you can also reach to us on our [gitter channel](https://gitter.im/getferdi/community) or the [stackoverflow room](https://chat.stackoverflow.com/rooms/237341/ferdi).
