### ISSUE TITLE
Ferdi crashes after start

### ISSUE THREAD

**Issue by cdjost** [getferdi/ferdi#1997]
When starting ferdi it closes immediately. I get the following error on the console: 
```[23124:0928/092209.110952:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.```
OS: Ubuntu 20.04

**Comment by jaroslaw-buszowiecki** [comment]
Maybe try to turn off enableGPUAcceleration in settings.json?

**Comment by potchin** [comment]
Also ran into this today after upgrading from Fedora 34 to 35. Current workaround is to disable GPU acceleration...

```
$ grep GPU ~/.config/Ferdi/config/settings.json 
  "enableGPUAcceleration": "false",

```

**Comment by basghar** [comment]
> Also ran into this today after upgrading from Fedora 34 to 35. Current workaround is to disable GPU acceleration...
> 
> ```
> $ grep GPU ~/.config/Ferdi/config/settings.json 
>   "enableGPUAcceleration": "false",
> ```

Doesn't work for me. I am also on Fedora 35 with Nvidia graphics card.

**Comment by djheroez** [comment]
I got this same error after an upgrade to Fedora 35. Workaround for me is to run it with `--no-sandbox`

**Comment by Bananaman** [comment]
@vraravam I have insight into this issue.

Chromium broke on glibc 2.34 due to using `clone3()` syscall. They patched Chromium in October or September to no longer use `clone3()` which stopped the crashing.

Electron imported the patch and also backported it to a bunch of older Electron versions. All this happened in September/October too.

The solution to fix Ferdi is to update to a newer version of Electron.

The workaround in the meantime is to start Electron with `--disable-gpu-sandbox`.

**Comment by Bananaman** [comment]
By the way, the official Discord client has the same issue of using an old version of Electron and therefore crashing. I alerted their developers to it via 2 methods, about a month ago, and they still haven't updated to a fixed version of Electron. Sad times.

**Comment by Bananaman** [comment]
I see that your nightly 5.6.4 pre-release has updated to Electron 15.3.2, which I think has the Electron bugfix (it seems new enough to have the fix).

**Comment by Bananaman** [comment]
I decided to try Ferdi again. Latest flatpak version 5.6.5. I won't try the native package again.

But the flatpak seems to work well now.

**Comment by djheroez** [comment]
5.6.5 fixed this issue for me too.
