### ISSUE TITLE
Unable to upgrade from the Settings screen to a beta version

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#205]
**Describe the bug**
Unable to upgrade to beta

**To Reproduce**

1. Go to Settings
2. Click on 'Include beta' versions
3. Click on 'Check for updates'
4. Nothing happens - even though the github page says there are betas available. (currently 5.4.0-beta.4 is available)

**Expected behavior**
I should have been able to upgrade to the `5.4.0-beta.4` beta

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser Ferdi
- Version 5.3.3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vantezzen** [comment]
As far as I know Franz has the same problem. It sometimes takes a while or a restart for it to see beta updates.

**Comment by kytwb** [comment]
I think it's because we have introduced the app signing/notarizing in [5.3.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.3.4-beta.3). The in-app updater doesn't work for unsigned app on macOS Catalina. The 5.3.3 being not signed/notarized, you will have to manually update to 5.4.3-beta.3 or greater for the in-app updater to work.

Please re-open if you think this is something else or if it did work since you opened the issue, which would mean the issue lays somewhere else.
