### ISSUE TITLE
Slack - Notification badge appears/disappears as conversations are scrolled

### ISSUE THREAD

**Issue by kmontag** [getferdi/ferdi#2203]
**Bug description:**

In Slack workspaces with a lot (> ~35) groups or conversations, the notification badge for an unread conversation (in the app as well as the system tray/system icon) appears and disappears as the Slack conversation pane is scrolled. This means that to reliably check for new messages in such workspaces, one needs to open the service and check for them manually.

**Steps to reproduce:**

Open a Slack workspace with many groups or conversations, and receive a message in a conversation near the bottom of the list. Scroll through the conversations pane. The notification badge for the message will appear as you get closer to the bottom, and disappear as you get closer to the top. Whenever the badge state changes, the Ferdi tray icon will bounce.

**Expected behavior**

The notification badge should appear regardless of the scroll state of the Slack window.

**Screenshots**

Screen capture (cropped for privacy): https://user-images.githubusercontent.com/388637/140989148-7b9b93b7-8514-438e-8873-70ea99b04438.mov

**Environment:**

- Operating System:  macOS Big Sur (M1)
- Ferdi Version:  5.6.3
- Slack Recipe Version: 1.3.3
- Server:  Using without an account

- Debug information: can provide if needed

**Comment by vraravam** [comment]
This looks like some sophisticated DOM manipulation by Slack where they remove the nodes as they disappear from the viewport while scrolling. We simply use the following selectors to gather the unread badge count: https://github.com/vraravam/recipes/blob/1e2a7c3ba221baa1bca04db8f9231a3a9d35e1a7/recipes/slack/webview.js#L12

I would suggest the following steps:
1. Please move this ticket to the https://github.com/getferdi/recipes repository since this issue is specific to an individual recipe
2. Please help finding the correct css selectors that can work irrespective of the nodes that are visible in the viewport.

I dont use slack and so cannot setup my machine to help debug the above.
