### ISSUE TITLE
Outlook email requires type in username every day.

### ISSUE THREAD

**Issue by ibin7777** [getferdi/ferdi#2522]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/getferdi/ferdi/issues) for a bug report similar to mine, in vain

### Steps to reproduce

1. wake up in a new day.
2. open my windows PC
3. open Ferdi
4. switch to my outlook tab
**5. requires me to login**
6. type in the mail address(username)
7. no need for the password, goes straight in.

### Debug link

Debug link failed to produce, stuck at this page

### Screenshots

![image](https://user-images.githubusercontent.com/64576479/161757532-c762deb5-9285-4d89-a954-793f5586d20b.png)
![image](https://user-images.githubusercontent.com/64576479/161757312-005c2de9-dc4c-407e-b589-d37f8dec7b36.png)

**Comment by ibin7777** [comment]
Update to the issue:

I have confirmed that not just every day, but every time I open the Ferdi software it asks me to login.

**Comment by SvenAbels** [comment]
I can confirm this but it only happens when accessing Outlook personal (i.e. live.com) and not when using outlook business (i.e. Office 365). As a workaround, edit the service, click on "Self hosted" and specify "https://outlook.live.com/mail/0/" as URL. Tnhis will keep you logged in.

I assume that the problem is related to some type of redirect always leading to the login form.

**Comment by ibin7777** [comment]
> 

Thank you for the reply!

Yes it indeed works.
