### ISSUE TITLE
[Question] How to use ferdi by itself ?

### ISSUE THREAD

**Issue by beppe9000** [getferdi/ferdi#298]
I wanted to use Franz in a self-contained (not self-hosted!) fashion. The only communication should be with the actual services. Does Ferdi require a server to work? Can it be setup as to not  require a server? ("require" as in "I have an airgapped laptop that can only connect to whatsapp servers")

If not, I would like to suggest that as a feature (maybe bundle recipes?).

**Comment by vantezzen** [comment]
We added the option to use Ferdi without an external server in v5.4.0. You should see the option to "Use Ferdi without an account" when you are on Ferdi's welcome, login or sign up screen. This will save Ferdi's options completely locally on your computer. Ferdi v5.4.0 also ships with Ferdi's complete recipe repository (see https://github.com/getferdi/recipes) build-in.
Please keep in mind that this is a relatively new feature and they might still be some bugs. Currently known bugs:
- The internal database will sometimes be created in read-only mode on Windows (file at "%appdata%/Ferdi/server.sqlite"). This can be fixed by disabling write protection in the Windows Explorer.
- The internal server has an invalid response on some Ferdi versions. Update to 5.4.1-beta.5 should fix this.

We advice you to enable beta updates in Ferdi's settings when using this feature.

**Comment by beppe9000** [comment]
Thanks! I got a couple of glitches that make ferdi unusable to me, tough.

Service button not working. Probably the server issues
![button not working](https://i.imgur.com/igACUrV.gif)

Other than that there is heavy update check trolling...
![update trolling](https://i.imgur.com/6VUmMGz.gif)
