### ISSUE TITLE
Update recipes from internal recipe repository

### ISSUE THREAD

**Issue by vantezzen** [getferdi/ferdi#328]
Ferdi currently has no way of checking if the internal recipe repository (https://github.com/getferdi/recipes) has a newer version than the installed version.

Ferdi will unpack the recipe .tar.gz file once during service creation and will only update recipes when the server reports it.
It would be best to implement some sort of check (probably using the internal `all.json` that contains version numbers for all recipes) to check for newer local versions without having to rely on the server.

A feature like this would be pretty critical as we can't force recipe updates to fix bugs in recipes otherwise.

**Comment by vantezzen** [comment]
Implemented via 0a89e919

**Comment by dankessler** [comment]
Does this actually work? I'm running the 5.4.4 beta (I installed the beta3 dmg although Ferdi reports it's 5.4.4 beta1). Either way, the 5.4.4 beta1 and up should have this fix included. However, I can see that my slack recipe is not the same as the one in ferdi/recipes. Notably, [this line](https://github.com/getferdi/recipes/blob/master/uncompressed/slack/webview.js#L44) which fixes indirect message counts with the new slack layout, and [this line](https://github.com/getferdi/recipes/blob/1392757b077c8ce582f00a1e47b35affcc448058/uncompressed/slack/webview.js#L12) which fixes automatic slack team icon import also due to the change in slack's layout. 

I don't understand the inner workings of Ferdi well enough yet to understand from this diff if there's something stupid I'm failing to do or what.
> Implemented via [0a89e91](https://github.com/getferdi/ferdi/commit/0a89e919b3caf4d4935d135d687ad5b31bdc4441)

**Comment by vantezzen** [comment]
At least in my tests, the implementation seems to work. Depending on your version it could however be that it doesn't ship with the updated recipe yet - I don't know when we updated the Slack recipe.

**Comment by dankessler** [comment]
Ah perhaps I misunderstood what was meant by:

> Ferdi currently has no way of checking if the **internal recipe repository** (https://github.com/getferdi/recipes) has a newer version than the installed version.

(emphasis mine). Since the URL was right next to it, I assumed that Ferdi would actually poll the `getferdi/recipes` repo for updated recipes and then overwrite whatever is on the local machine (for me they're in `~/.config/Ferdi/recipes`). A careful reread talks about checking for newer **local** versions so I presume there's something else that ships with the install that is distinct from what is in my home directory, and the issue being fixed here is that old recipes in the home directory would not get overwritten even when installing a new Ferdi. Is that right? Sorry for the confusion!

I now see that recipes is submodule-d into the ferdi repo, which seems like further confirmation of this. If I want my recipes to be "as fresh as possible" is my best course of action to just overwrite whatever I have locally with the corresponding files from getferdi/recipes's master branch?

**Comment by vantezzen** [comment]
Sorry if that wasn't clear yet. As you already saw now, whenever we create a new version of Ferdi, the application bundle ships with the newest recipe files _at that time_.

If you want to use the newest version possible, you can download the corresponding folders inside the `uncompressed/` folder and overwrite the folders inside `%appdata%/Ferdi/recipes` (Windows), `~/Library/Application Support/Ferdi/recipes` (Mac) or `~/.config/Ferdi/recipes`(Linux) with those.

**Comment by MurzNN** [comment]
I post feature request with similar idea here https://github.com/getferdi/ferdi/issues/819
