### ISSUE TITLE
Open Telegram tg:// link in default browser

### ISSUE THREAD

**Issue by Matthieu42** [getferdi/ferdi#380]
**Is your feature request related to a problem? Please describe.**
Sometimes i open links in Ferdi and I can't copy them to clipboard, so I'm stuck with "ferdi embedded browser"

**Describe the solution you'd like**
I would the option to choose in the settings : Open links with ferdi browser OR with default browser. 

If this feature request is approved, I can maybe try to dev it.

**Comment by Gaboris** [comment]
Odd because both Ferdi AND Franz does that since day one by default.

The open in internal browser seems more of a bug in some systems or something.

Heck, I'd be more interested in the option to set what browser to use and not default to the system default. :thinking: 
It's already a request on Franz's Github that I also supported.

**Comment by Matthieu42** [comment]
Ok, after some testing, it appear that this behaviour appear only in Telegram. In FB messenger and steam chat it open my default browser (Firefox) correctly. I've only tested this 3 services.

Opening a link in Telegram : 
![image](https://user-images.githubusercontent.com/18295583/74591089-33b11500-5015-11ea-9cbe-caf4d10fcacb.png)

**Comment by Gaboris** [comment]
Still seems to be a local problem since both Telegram and Messenger opens up my Firefox browser even if it's turned off. Messenger sometimes needs to be clicked twice, but still.

I'll admit that a lot of people have this problem. It involves all kinds of other messages, pages or functions, but it's actually not intended to be like that and the problem is that somehow the devs would need to reproduce this in order to figure out how to solve it. What system are you using with what settings involving Ferdi?

Where is Ferdi installed? Maybe it's not on the system drive just as a quick guess?

**Comment by Matthieu42** [comment]
Windows 10, Ferdi 5.4.3 installed in system drive (AppData)
But after some digging, I've spotted the issue :

**Comment by Matthieu42** [comment]
Windows 10, Ferdi 5.4.3 installed in system drive (AppData)
But after some digging, I've spotted the issue :
`<a href="tg://unsafe_url?url=https%3A%2F%2Fitch.io%2Fs%2F28060%2Fits-free" target="_blank" rel="noopener noreferrer">[link]</a>`
Telegram link use "Telegram protocol" for external link. If I edit and delete tg://unsafe_url?url=, it opens correctly in my browser. 
And the reason why it's the same behaviour for everyone, it's maybe juste because "tg://" is not handled the same depending on the configuration.

**Comment by Gaboris** [comment]
That might be a good point to start at, but also curious where did you get that snippet from? Ferdi uses webview to display its content so you shouldn't be able to see the elements. Or did you get that from an actual browser?

**Comment by Matthieu42** [comment]
With ctrl + alt + i, you can open the chromium debug tools, like in any electron app

![image](https://user-images.githubusercontent.com/18295583/74592523-7a593c00-5022-11ea-8c09-0ce617f1f529.png)

**Comment by Gaboris** [comment]
Yes and for me it shows that the service is running enclosed within a webview element and I actually can't see the contents.

Maybe THAT is the reason. Maybe your client isn't actually the "real" Ferdi process, but maybe it's running within Ferdi's internal browser like the option to run custom webpages and THAT is why your default browser gets ignored. Because it's ALREADY within a browser. :thinking:

**Comment by vantezzen** [comment]
Ferdi implements logic to test if it should open a link you clicked in the browser or on Ferdi:
https://github.com/getferdi/ferdi/blob/f07b3f706d29959e22b652620a466a5af30b892a/src/webview/recipe.js#L272-275

We probably need to refine this test to make sure it works with this.

**Comment by Gaboris** [comment]
Cool, that might be the case then, but I'm curious why haven't I ever seen this behavior and how Matt able to see the code for the client?
Was my guess about it somehow being opened in the internal browser right or is there something I'm still not getting right?

**Comment by kytwb** [comment]
@Gaboris 

<img width="307" alt="Screen Shot 2020-03-03 at 4 10 09 AM" src="https://user-images.githubusercontent.com/412895/75739331-e915e500-5d04-11ea-9c2c-0731925fdb8e.png">

Toggle Developer Tools (Ferdi)
Toggle Service Developer (Service)

**Comment by Matthieu42** [comment]
Thanks, this solution looks perfect for me !
I'm closing the issue
