### ISSUE TITLE
Paste as plain text from right-click context menu

### ISSUE THREAD

**Issue by agamerj** [getferdi/ferdi#413]
Hello, I have been using your Ferdi. But, there is one thing which is missing from your software that is Paste as Plain Text.

If you right click in any text, you will see this option in Chrome. But, I think that should be added into the Ferdi also. Specially into Gmail or any other Mail.

Thanks.

**Comment by kytwb** [comment]
@agamerj Thanks for using Ferdi and coming up with the suggestion!

**Comment by agamerj** [comment]
Well, this can be added or no? (Asking if it's feasible) If so, then how long it would take according to your current schedule?

**Comment by kytwb** [comment]
The project is based on Electron, so if [Electron offers the possibility to read the clipboard as plain text](https://www.electronjs.org/docs/api/clipboard#clipboardreadtexttype), I guess we should be able to paste things as plain text. I don't use this feature personally so I won't spend time working on this in the foreseeable future. Please feel free to come up with a pull request to implement it, otherwise you'll have to wait for another generous contributor to implement it for you.

**Comment by kytwb** [comment]
Some people are experiencing issue with the contextual menu (that would be higher priority, see https://github.com/getferdi/ferdi/issues/357); maybe that could be taken a look at while working on fixing the issue.

**Comment by kytwb** [comment]
@agamerj This should be available in our next release. I have fixed the context menu issue and added a "Paste as plain text" option when applicable while I was at it. More details in the pull request referenced above.

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3).
