### ISSUE TITLE
Hide Mobile Version Notification of Telegram

### ISSUE THREAD

**Issue by agamerj** [getferdi/ferdi#414]
Hello, Whenever I shrink the Telegram Window, it gives me an annoying option of using Mobile Version.

How can I permanently OFF that option or that window and make desktop as permanent option unless I change it manually myself from settings or something?

I don't want that prompt for changing the style.

**Comment by kytwb** [comment]
@agamerj could you provide more info, maybe screenshots please?

**Comment by agamerj** [comment]
![sx-28-February-20-3269](https://user-images.githubusercontent.com/9323342/75555158-b7c9ba80-5a61-11ea-969b-c89d69537105.png)

You can see in the above screenshot that as I have shrink the window, it gives this annoying message everytime.

**Comment by kytwb** [comment]
I guess this is the normal behavior of the Telegram service then. We are introducing a new feature soon that will enable you to change the default appearance/behavior of services (see https://github.com/getferdi/ferdi/pull/401). It will ship in the next release but will require for you to be able to address this on your own using some code in the `user.js` file introduced via the pull request I previously linked.

**Comment by agamerj** [comment]
I don't know coding, that's the sad part.

**Comment by kytwb** [comment]
@agamerj I got you!
As previously said, and since [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2), you can now add custom JS/CSS in services:

<img width="548" alt="Screen Shot 2020-03-02 at 3 37 38 AM" src="https://user-images.githubusercontent.com/412895/75641043-3deb2a00-5c37-11ea-8206-c1b4f64aacd6.png">

A quick solution for you would be to add the following in `user.css`:

```css
.modal,
.modal-backdrop {
  display: none !important;
}
```

This will hide all modals in Telegram. I can't guarantee you won't miss important modals that would break normal usage of Telegram.

PS: Please consider [supporting Ferdi development](https://opencollective.com/getferdi#section-contribute) if you can! 🙏
