### ISSUE TITLE
Gmail and Keep do not open on the grounds that the browser is not secure.

### ISSUE THREAD

**Issue by doprado** [getferdi/ferdi#435]
Gmail and Keep do not open on the grounds that the browser is not secure.

![gmail](https://user-images.githubusercontent.com/15928422/75812849-b227e980-5d6d-11ea-9ef2-7819671ca32c.png)

**Comment by kytwb** [comment]
Please refer to https://github.com/getferdi/ferdi/issues/264 🙏 I have renamed the title of https://github.com/getferdi/ferdi/issues/264 to include "Google Issues Megathread" as the issue was pinned but couldn't be easily identified as containing the infos it contains regarding the Google issues. 
Thank you!
