### ISSUE TITLE
Two different versions installed automatically

### ISSUE THREAD

**Issue by dqos** [getferdi/ferdi#453]
**Describe the bug**
Yesterday I downloaded the latest version of Ferdi, then after installation Ferdi prompted that there was an update. Then I updated and noticed two different versions of Ferdi in my control panel: 5.3.3 and 5.4.3.

I don't want to uninstall one, because I assume it will completely uninstall Ferdi. I hope this will not happen in the future, because I don't want to have Ferdi installed more than 1 time 😄 

**To Reproduce**
1. Download latest release and install it.
2. Follow the Ferdi prompt to update the app.
3. See apps in control panel.

**Expected behavior**
The app should uninstall OR should overwrite the version in control panel.

**Screenshots**
![](https://i.imgur.com/ommxuI5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Version: 5.3.3

**Comment by SMile61** [comment]
Hi, 
I noticed the same issue. 
Moreover, I had to uninstall and reinstall the 5.3.3 version because Gmail (Franz modified) recipe didn't work anymore after updating

**Comment by ckkoen** [comment]
Yes indeed, I noticed this to when I first tried to install Ferdi a couple of weeks ago. The getferdi.com website says 'Download Ferdi 5.4.3', but when you click the Windows install button, the following URL is being used:
https://github.com/getferdi/ferdi/releases/download/v5.3.3/Ferdi.Setup.5.3.3.exe

Can this be changed please? Even manually changing the url doesn't work, so it seems the 5.4.3 Windows version isn't uploaded to the Ferdi website.. I was able to install the newest version without first installing the old version by downloading it from GitHub instead of the Ferdi website via this url:
https://github.com/getferdi/ferdi/releases/download/v5.4.3/Ferdi-Setup-5.4.3.exe

**Comment by vantezzen** [comment]
> Can this be changed please?

This change was made intentionally due to https://github.com/getferdi/ferdi/issues/253#issuecomment-589790810 and the confusion this bug caused for many users. We will update the Windows link once 5.4.4 or 5.5.0 is released.

Still, this bug will probably also occur with future updates, not only with this once, so we should see how we can fix this nonetheless.

**Comment by ckkoen** [comment]
> > Can this be changed please?
> 
> This change was made intentionally due to [#253 (comment)](https://github.com/getferdi/ferdi/issues/253#issuecomment-589790810) and the confusion this bug caused for many users. We will update the Windows link once 5.4.4 or 5.5.0 is released.
> 
> Still, this bug will probably also occur with future updates, not only with this once, so we should see how we can fix this nonetheless.

Maybe state this on the website then? Not everyone can be expected to sort through all the GitHub issues. And apparently users are still being asked to update to the newest version when they download the old version from the website. So if they don't know about this problem, they will update their version & still experience the problem. If they saw a short notice about this while downloading it from the website, they might choose not to update afterwards.

**Comment by vraravam** [comment]
Closing this issue - since we are getting ready to release 5.6.0
