### ISSUE TITLE
Why does Ferdi handles non-chat services ?

### ISSUE THREAD

**Issue by Nokia808** [getferdi/ferdi#581]
Hi dear developers. This is a personal opinion if you see it incorrect you can close it. 
Dear, why you include non-chat services in Ferdi ? Examples are:

- Gmail
- Protonmail
- Google drive

Is this wise ? Isn't better to concentrate on one field to make Ferdi much better ? Isn't making Ferdi deal with multiple field make it less powerful in all these filed ?

To me I see if Ferdi concentrate only on chat/messenger services, it will be much better in this field than if deal with other field like email & cloud storage services ..... 

For email services we already have excellent applications like: Thunderbird, Claw mail, Postman, Evolution ...... All these applications able to handle OpenPGP encryption that we should encouraged, so why we make peoples use Ferdi to utilize such email services while it is (Ferdi) not able to handle OpenPGP by itself like Thunderbird ? Trying to make Ferdi a full featured email client will interfere with making it excellent chat/messenger client, as I see (please correct to me if I'm wrong).

This critic not only to Ferdi but also to Thunderbird which try to include chat service like Jabber ......

**Comment by vantezzen** [comment]
Thank you for your feedback on Ferdi's services.

> Dear, why you include non-chat services in Ferdi?

At least in our opinion, Ferdi isn't limited to being an application for your chats: Ferdi should be the place you can keep all your services that you have to have open all the time.

Ferdi is meant to be used to increase your productivity and give a better interface to organise your services.
At work I use WhatsApp but also "non-chat" services like GMail, GitHub and Trello to communicate with my colleagues. Looking at the services our users create, at least 50% of created services are not traditional chat services, e.g. Trello, XING or Google Drive.
We also use Google Drive at work to store important documents and I like to keep this in Ferdi instead of my normal browser.

> Isn't making Ferdi deal with multiple field make it less powerful in all these filed?

Please keep in mind that at its core, Ferdi is simply a chromium browser. To add a service like Trello or ProtonMail, we don't have to do a lot of work. All Ferdi needs in order to support a service is a [Service Recipe](https://github.com/getferdi/recipes) which is only a few lines or code. Additionally, for most services, other GitHub users already created these recipes, so we only have to insert them into our recipe repository.

> For email services we already have excellent applications
> Trying to make Ferdi a full featured email client will interfere with making it excellent chat/messenger client

Again, Ferdi is simply displaying and enhancing the online versions of mail services. We are not building any email client!
Most users like and are familiar with the web version of GMail or Protonmail but simply don't like having them in a browser tab with all their other content - they want to have it seperated into a specialised browser that gives them the same interface while giving them features to better manage those services.

This is what Ferdi is about: Giving a better wrapper around these services. A normal Chrome or Firefox browser _can_ display those services but Ferdi gives you a better experience around using them, e.g. with global do-not-disturb, native notifications and more.
