### ISSUE TITLE
this._hibernate is not a function

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#605]
**Describe the bug**
Picked up from errors reported in Sentry. The Hibernation feature is **not affected** by this error; it works even when this error occurs (so tagged low priority and good first issue).

**Expected behavior**
Understand and properly handle the case where `this._hibernate` is undefined.

**Screenshots**
<img width="1198" alt="Screen Shot 2020-04-19 at 6 41 10 PM" src="https://user-images.githubusercontent.com/412895/79696638-8608ef00-826d-11ea-892f-08fdc6974fd8.png">

**Comment by vantezzen** [comment]
This bug is due to:

https://github.com/getferdi/ferdi/blob/2205849cd0a4ddfc33d3785b9aadade17fe5fe76/src/stores/ServicesStore.js#L159-L162

The code got introduced when merging Franz 5.5.0-beta.2. Franz now has its own hibernate feature but as Ferdi's one is more customisable, I kept ours instead and removed the code from Franz's hibernation. It looks like I simply oversaw that piece of code - I've removed that via #609
