### ISSUE TITLE
Double-check in-app / brew updates

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#61]
See https://github.com/getferdi/ferdi/issues/19#issuecomment-533257404:

> I tried both, but neither the in-app update checker or `brew cask outdated` is reporting any available updates to install.

**Comment by PandaWhisperer** [comment]
Copied from [here](https://github.com/getferdi/ferdi/issues/19#issuecomment-533753595):

> So while Ferdi still doesn't show up when I run `brew cask outdated`, I do seem to be able get the newest version by running `brew cask upgrade ferdi`.
>
> It's downloading 5.3.3 right now. Perhaps brew cask outdated is broken, or casks just work differently?

**Comment by vantezzen** [comment]
The auto-updater on mac currently does not work due to:

Build-in updater: The build-in updater uses the `electron-updater` package. This package requires the updated application [to be signed](https://www.electron.build/auto-update) in order to work. As Ferdi releases are currently not yet signed, this method won't work.

Brew cask: `brew cask outdated` shows a list of outdated casks **that do now auto-update themselves**. Ferdi however, [does auto-update](https://github.com/Homebrew/homebrew-cask/blob/ea3b252dee9a46de14d751dba96a8f4e24bb34dc/Casks/ferdi.rb#L10) and thus doesn't get shown.
You'll have to run `brew cask outdated --greedy` in order to see if Ferdi is outdated.

**Comment by kytwb** [comment]
@vantezzen Thanks for the explanations! Awaiting  https://github.com/getferdi/ferdi/pull/52 then.

**Comment by kytwb** [comment]
<img width="311" alt="Screen Shot 2019-09-24 at 9 25 47 PM" src="https://user-images.githubusercontent.com/412895/65520533-ea4f1480-df11-11e9-9718-486367edaae2.png">

<img width="237" alt="Screen Shot 2019-09-24 at 9 32 48 PM" src="https://user-images.githubusercontent.com/412895/65521179-01dacd00-df13-11e9-9801-b142baa9b1af.png">

<img width="297" alt="Screen Shot 2019-09-24 at 9 33 19 PM" src="https://user-images.githubusercontent.com/412895/65521181-01dacd00-df13-11e9-8ba2-c777a8de1858.png">
