### ISSUE TITLE
AVG detects the 5.5.0-gm.2 update as a very serious malware

### ISSUE THREAD

**Issue by Gaboris** [getferdi/ferdi#633]
I downloaded the update through Ferdi and AVG blocked it through behavior analysis, but also gave the same alert after checking the file itself.

I've submitted the installer to be reviewed so they can flag any false positives themselves, but if others have this same problem you might need to look into what caused this detection.

**Comment by kytwb** [comment]
Can you please share a screenshot of what you get in AVG?

**Comment by kytwb** [comment]
We updated Electron to 8.2.3 and implemented screen sharing for MS Teams in 5.5.0-gm.2. Not sure if AVG is somehow detected something new in the Electron binary or if it's because of the code that is present to share screen in the MS Teams recipe. That's all I can think of for now. Closing as to not afraid other people, but happy to continue the discussion 🙏

**Comment by kytwb** [comment]
I have also submitted 5.5.0-gm.2 Windows binary to VirusTotal, report available [here](https://www.virustotal.com/gui/file/380864d9bb71c0530c1a5255395c9820e9bb6e618f6a90c737e49fcdcaf625f1/detection) for what it's worth.

**Comment by Gaboris** [comment]
Hey I'm back. Sorry AVG makes it hard to get exact names now and it just says "FileRepMalware" while on the first launch it had a big fancy popup with an actual malware name, but I think it's not important right now. I'll give it a few days and I'll try again then.

**Comment by kytwb** [comment]
See also https://github.com/getferdi/ferdi/issues/112
