### ISSUE TITLE
Make Ferdi avaliable in Chocolatey

### ISSUE THREAD

**Issue by cdjost** [getferdi/ferdi#637]
Hi,

it would be great if one could install and update ferdi easily with chocolatey (https://chocolatey.org/docs/create-packages).

**Comment by vantezzen** [comment]
Related: https://chocolatey.org/docs/create-packages

**Comment by digitalcoyote** [comment]
I can make a choco package and maintain it or help you to setup to maintain it. I use an AU repo (the chocolatey recommended way) that uses your releases to automatically publish updates to chocolatey. Since you added hte Hacktobberfest label, i'm going to go ahead and get started.

If you want to take it over or just be added as a maintainer, let me know. (being a maintainer gives you rights to the package on Chocolatey)

**Comment by digitalcoyote** [comment]
https://chocolatey.org/packages/ferdi in review

**Comment by vdurante** [comment]
Is it possible to automate publishing of Ferdi to chocolatey?

**Comment by vraravam** [comment]
@vdurante - I am not a windows user, but if you can point me to any docs on how to publish to chocolatey - I will try to see how to set it up with the CI process?

**Comment by vdurante** [comment]
@vraravam maybe @digitalcoyote could help, since he is the mantainer of chocolatey's pacakge. You can find how he does it [here](https://github.com/digitalcoyote/chocolatey-packages/tree/master/ferdi). 

I believe you would need to update .nuspec and [push](https://docs.chocolatey.org/en-us/create/commands/push) the package.

**Comment by vraravam** [comment]
Thanks @vdurante - I have created a PR for this now: https://github.com/digitalcoyote/chocolatey-packages/pull/24

**Comment by vdurante** [comment]
Thank you, @vraravam

**Comment by mhatvan** [comment]
Ferdi v5.6.0 is online at: https://community.chocolatey.org/packages/ferdi

@vraravam Is the automatic update process in place? Then we can close this issue.

**Comment by vraravam** [comment]
According to [this comment](https://github.com/digitalcoyote/chocolatey-packages/pull/24#issuecomment-889907608) - the auto-update should be working. Lets close this ticket for now. Can reopen if this is still an issue.
