### ISSUE TITLE
Spell checking in multiple languages at the same time

### ISSUE THREAD

**Issue by kmgalanakis** [getferdi/ferdi#668]
**Describe the bug**

I'm not sure if this should be considered as a bug but is there the option for an app (Skype for example) to be able to offer spell checking suggestions for more than one language? For example, when I open skype in Chrome, my browser is set to check spelling in all my languages 

![image](https://user-images.githubusercontent.com/1268089/80458021-dd2b5580-8938-11ea-9d3f-20fade4c619c.png)

This way in my Greek chat, chrome is offering me greek suggestions while in my English chats it offers me English suggestions.

Is something similar possible here?

**Comment by Gaboris** [comment]
When Ferdi just forked off of Franz we had the option to change sleppchecking settings from the contextual menu to do stuff like change the language or add words to dictionary.

This was taken away when we had to revert back to Google's built in function since the custom one was crashing internally almost always.

If this is something we can do then we might also consider enabling the whole functionality as well. :+1:

**Comment by vantezzen** [comment]
This will get implemented via #809:

![Screenshot 2020-06-14 at 12 38 08](https://user-images.githubusercontent.com/10333196/84591088-e8c8d200-ae3b-11ea-9e48-a8517ee0f9c8.png)
