### ISSUE TITLE
Add a way to mock browser version / updated date

### ISSUE THREAD

**Issue by arthurprs** [getferdi/ferdi#709]
**Is your feature request related to a problem? Please describe.**

There are other reports of people having "browser is not supported/outdated" in other services etc.. So I think this will cover a wider range of problems.  

Right now I'm locked out of Slack because it uses DUO for the 2 factor authentication. DUO has obnoxious restrictions on how up to date the browser must be.

![image](https://user-images.githubusercontent.com/715958/80948707-f6c61480-8df2-11ea-931a-5518b30485da.png)

**Describe the solution you'd like**
Add an option to override the browser version (etc..) reported to the embedded pages.

**Describe alternatives you've considered**
:no_entry_sign: 

**Additional context**
:no_entry_sign:

**Comment by nicosebastian93** [comment]
Did you already tried to modify the user agent for this service? For Google Mail and Google Calendar it worked for me. But, in general, we would need to be able to do that on an easier way or they need to update the user agent or browser with every update of Ferdi. I think the root-cause is, that it's an issue of Franz. I tried Franz before I found Ferdi and didn't want to pay for it because the most of my services didn't worked of such issues with the browser version.

You can try the user-agent form here: #264

**Comment by mahadevans87** [comment]
I can take this up

**Comment by vraravam** [comment]
Please try with the nightly builds from [here](http://github.com/vraravam/nightlies/releases) - this exposes the ability to the user to control the user-agent via the UI as opposed to editing files in the Ferdi profile. Please do be aware of the **unsigned nature** of the builds in this repo - while we work on fixing the issue with signing of our build artifacts.

**Comment by mhatvan** [comment]
Changing the user agent is possible in Ferdi through the "Settings" > "Advanced" tab.
