### ISSUE TITLE
Loop after passlock

### ISSUE THREAD

**Issue by halcyon101** [getferdi/ferdi#712]
Ferdi Loops on purple screen after enabling passlock/screenlock

version 5.5

**Comment by vadosl** [comment]
Yes , the same issue on 5.5 Win7 and 5.5 Ubuntu 18.04. To fix the bug and start app I must manually edit fields   "lockingFeatureEnabled": false,
  "locked": false.

**Comment by keunes** [comment]
Same as #543? https://github.com/getferdi/ferdi/issues/543#issuecomment-620490377 fixed it for me (but also made me realise the 'password' is stored in plain-text and locking can super-easily be removed so doesn't make any sense at all to use for example at work or public computers).

**Comment by mahadevans87** [comment]
@keunes  The password is not stored as plain text. A hashed value of the password is stored which means you will not be able to use that password in the settings file to log back in. However, the issue here is that anyone can go to the settings screen and change the locked value to false and login. We are working on that issue separately and will provide you an update once it's complete.

**Comment by keunes** [comment]
@mahadevans87 This (plain-text password) was only fixed in #694 and not available on many systems yet (including mine), if any.

The issue that it's possible to change settings by accessing & editing the settings file (not the screen, as you are talking about) will hopefully be covered following #729 which I created. But that's different from #543 (of which I believe this issue is a duplicate).

**Comment by kytwb** [comment]
Thank you everyone! 🙏
