### ISSUE TITLE
Review react-intl usage

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#753]
As per https://github.com/getferdi/ferdi/pull/717#discussion_r422616489, we noticed some issues with file paths generation via Windows contributors. We don't use file paths as far as we know, so @mahadevans87 suggested we set `extractSourceLocation` to **false**.

This might be something to do once we have less on-going pull requests to reduce conflicts.

**Comment by kytwb** [comment]
While we're at it, I think it would be helpful to remove unused strings inherited from Franz.

**Comment by mahadevans87** [comment]
That makes sense. Thanks for bringing this issue up @kytwb

**Comment by mhatvan** [comment]
I upgraded `react-intl` and moved from deprecated `babel-plugin-react-intl` to `babel-plugin-formatjs` in https://github.com/getferdi/ferdi/pull/1920

`formatjs` detects unused translation strings automatically and deletes them.

Also, we don't use `extractSourceLocation` anymore, since we don't seem to need the location paths.
