### ISSUE TITLE
Next Update and Discord Community?

### ISSUE THREAD

**Issue by agamerj** [getferdi/ferdi#815]
Hi, I have two concerns with Ferdi!

1. When is the next update coming? It has been so long since the last one.

2. Can we have Discord Community now so that we can talk with the other users who uses Ferdi/Alternative?

Thanks.

**Comment by vantezzen** [comment]
Thank you for sharing your concerns about Ferdi.

> 1. When is the next update coming? It has been so long since the last one.

The last update was ca. 1½ months ago. We release new full updates every 3-4 months, so it isn't really that long ago.
If you want to get new updates more frequently and if you can live with some features being unstable, you can switch to out [nightly releases](https://github.com/getferdi/nightlies/releases) instead. We normally provide new nightly releases every 2 weeks.

> 2. Can we have Discord Community now so that we can talk with the other users who uses Ferdi/Alternative?

We try to keep all our communication on GitHub with GitHub issues so we won't open a Discord Community from our side. With GitHub issues, conversations stay open source and due to them being sorted into individual issues, you can quickly find existing conversations on a topic.
