### ISSUE TITLE
Norwegian language

### ISSUE THREAD

**Issue by larsmagnusherland** [getferdi/ferdi#840]
Ferdi has been translated fully into Norwegian in Crowdin

**Comment by larsmagnusherland** [comment]
I see the 5.6.0 beta is in progress, but it does not include the files from Crowdin.
I can't download from within Crowdin, so would take quite some time to copy-paste them over and then fork a translation.

**Comment by vantezzen** [comment]
I just merged the norwegian translations from CrowdIn into GitHub (see https://github.com/getferdi/ferdi/blob/develop/src/i18n/locales/no.json).

It's been some time since we last added a new language so I'm not quite sure if there is any more to do, but I just added Norwegian to the language list, which should make it available to select from withing Ferdi's next update.

https://github.com/getferdi/ferdi/blob/73d574be8d71f6cdd4209ea7b5926bd60f985869/src/i18n/languages.js#L28
