### ISSUE TITLE
Allow using security key for Google MFA

### ISSUE THREAD

**Issue by rgarrigue** [getferdi/ferdi#874]
**Is your feature request related to a problem? Please describe.**

I've a SoloKey (Yubikey equivalent) used for MFA on Google, Github, etc. Works fine with Firefox & Chromium. Can't use it in Ferdi. Not compatible says Google. I'ld like to use it though.

**Describe the solution you'd like**

I'ld like it to work. 

Eventually, if the issue is "by security design" (like a properly sandboxed / secured chromium), maybe an opt-in option in the Ferdi's service to allow using the security key would be purrrfect.

**Describe alternatives you've considered**

Actually I'm coming from Rambox, which has the same issue in a worse manner : it's endelessly loading waiting for the security key confirmation (issue 2521). 

Ferdi's way of failing is better as far as I'm concerned, at least I can fall back on Authenticator app / SMS.

**Additional context**

Google "nope" (in french, but clear enough I believe)

![image](https://user-images.githubusercontent.com/1872031/87062095-e5432380-c20c-11ea-86e6-66754af3cd86.png)

It does work for Github

**Comment by vantezzen** [comment]
There isn't really anything we can do about this. We've already had some existing problems with Google using some internal magic to decide whether it lets you log in to a device or not.
As you already mentioned, Ferdi fully supports authentification with 2FA USB Keys - the problem lies within Google.
