### ISSUE TITLE
Firebase instead of Ferdi-Server

### ISSUE THREAD

**Issue by jbouaziz** [getferdi/ferdi#909]
**Is your feature request related to a problem? Please describe.**
The feature would be to remove the dependency to Ferdi-server, add oauth2 support, centralise the user preferences in a single firebase database.

**Describe the solution you'd like**
I am working on a personal project that uses firebase as the main db and I'm trying to remove the dependency from Ferdi-server and centralise the user preferences (services, workspaces, etc.) in one place.

1. Is it possible to replace the local connections to Ferdi server?
1. If it is, where would you start? I saw mentions of internal server in the code but I'm a little confused.

**Describe alternatives you've considered**
Eventually trying to plug-in firebase on Ferdi-server and just replace the url in the app.

**Comment by vantezzen** [comment]
For your question: Most connections to the server are made in https://github.com/getferdi/ferdi/blob/develop/src/api/server/ServerApi.js so that would be the place to implement alternative server methods.

The mentions to Ferdi's internal server (https://github.com/getferdi/internal-server) you saw are there to implement the "Use Ferdi without an Account" feature. We wanted to add a feature, where users who don't want their data to be uploaded to a server can choose to store the data locally. As Franz, the project Ferdi is based on, doesn't offer such a feature, we decided to simply create a stripped-down version of the Ferdi server that runs locally.

Please note that we do not plan to switch our main Ferdi server over to a Firebase instance. We have a sponsorship with [DigitalOcean](https://www.digitalocean.com/), in which they will provide us with the server resources we need for the project. Additionally, we want to give users the possibility to host Ferdi's server software on their own servers without needing to rely on third-parties like Google.

**Comment by jbouaziz** [comment]
Thanks a lot for your insight @vantezzen, I managed to move a lot of features to firebase over the weekend, mostly in the `ServerApi.js` like you suggested. I'll close this issue as it is not an enhancement that you'll be implementing but will leave it in case somebody else is interested.
