### ISSUE TITLE
Protonmail logs me out periodically and whenever reloading service 

### ISSUE THREAD

**Issue by kelmee** [getferdi/ferdi#919]
Every instance of protonmail (custom url or using the built in service) logs me out periodically or when I reload the service. 
Also boots me out when I use the refresh button on the browser

**Comment by maxsubs** [comment]
new ferdi user here, I also get log off proton every time. This wasn't happening on Hamsket, so I'm not sure if this could be fixed somehow, can't we have an option to hibernate just protonmail when we close Ferdi?

**Comment by vantezzen** [comment]
You can disable hibernation for a single service in its service settings.

This issue will be thankfully irellevant soon though, as the new ProtonMail client (currently ProtonMail Beta) allows you to stay logged in when reloading

**Comment by maxsubs** [comment]
Yes, I know there's an option to hibernate not-used services, but this is only while Ferdi is open. I always close Ferdi while not using it, don't keep it running in background, so what I meant was that, when closing Ferdi, instead of close ProtonMail and Messenger, save tha state/hibernate these services and start from that state whenever Ferdi is reopened.
I'm also getting logged off of Messenger, which is a pain because I use a really long password.

**Comment by vraravam** [comment]
I use Protonmail with Ferdi 5.6.0 - and I dont see this behavior. I also have tried with hibernating the Protonmail service and still it works as expected: it remembers the logged-in state and continues from there.

Please reopen if you are able to give some reproducible steps.
