### ISSUE TITLE
Additional options for Dark Mode

### ISSUE THREAD

**Issue by justus-saul** [getferdi/ferdi#94]
After the implemntation of https://github.com/getferdi/ferdi/issues/71 I think the dark mode could use additional options regarding how it should be handled by the services:

When
[x] Join the dark force
there should be two additional options:
   [  ] Enable dark mode for services as well
   [  ] Enable universal dark mode for services with no own dark mode color scheme

I think the first option would be good for people who would like to have only ferdi itself in darkmode or want to configure a theme by themselves in the service itself.
The second option could help if the universal dark mode messes too much with some services. For me Office 365 isn't really usable anymore with the dark mode for example.

Maybe it would also make sense to add options like this on service level like:
If a `darkmode.css` is present then `[  ] Enable dark mode` otherwise `[  ] Enable universal dark mode`

**Comment by Gaboris** [comment]
I support this idea!

I think the new Dark Reader approach is messing with my original custom CSS and is either stopping them from getting applied or probably reverting their effects since a lot of my services randomly need a reload to go dark again and others that do have their own dark theme end up getting messed with.

So yeah, it would be best to set up separate options for each service.
One for DR's automated approach if someone doesn't want to make their own style, but also so people can disable it in case it messes with the original. This way you don't need to disable it in code for each service.
Another one for darkmode.css, BUT with an added upload or edit option so people don't have to navigate their local folders to find a service.

I'm still thinking if they should be exclusive so only one can be active at a time or if a custom style should be applied in case someone doesn't like what DR came up with.

**Comment by vantezzen** [comment]
> I think the new Dark Reader approach is messing with my original custom CSS

This shouldn't be the case, could you please provide more information? The code should only activate dark reader if no `darkmode.css` is available:
https://github.com/getferdi/ferdi/blob/master/src/webview/recipe.js#L122-L131

> BUT with an added upload or edit option so people don't have to navigate their local folders to find a service.

as suggested in #83. 


We will have to wait with implementing this until we set up our own server as the settings won't get saved to the Franz server, thus resetting your dark-mode settings every time you reload Ferdi.

**Comment by Gaboris** [comment]
In that case it seems that custom styles get blocked form getting applied. At literally random my Telegram or Messenger that doesn't have a built in dark theme for its web client comes up with its default light theme even though I have darkmode.css enabled and just by reloading the service it get applied.

I know that DR doesn't seem to detect if something already has a native dark theme so I'm not mentioning things like how it messes with Skype or IRCCloud since that would be better solved with those custom settings.

I did NOT know that Franz actually parses the settings they save. I just thought they get some JSON strings that they send back to us when needed, but now I get it.

**Comment by vantezzen** [comment]
I'll have to look into the problems with DarkReader overwriting existing darkmode.css themes.

I think Franz's API does some validation and only saves those settings that the official Franz client actually has. I had the same problem with the "Keep individual Workspace loaded" option, where I could save the option through a trick but I don't see any way to do this with services.

**Comment by Gaboris** [comment]
Got it. Thank you!

**Comment by probablykasper** [comment]
This is how dark mode looks for me currently. Most buttons are essentially invisible.
<img width="1356" alt="Screen Shot 2019-10-13 at 5 04 33 PM" src="https://user-images.githubusercontent.com/11315492/66717869-0c83d600-edde-11e9-924a-c63d1349f87f.png">

And for this one, it makes the middle of the background black, for some reason.
<img width="1356" alt="Screen Shot 2019-10-13 at 5 12 42 PM" src="https://user-images.githubusercontent.com/11315492/66717908-3e953800-edde-11e9-8035-c0f0cd5675fe.png">

**Comment by vantezzen** [comment]
I now added a toggle to the settings to disable the universal dark mode via c44cb8d and fixed the toggle in the service editing screen to disable dark mode for individual services via 129988f.
