### ISSUE TITLE
Skype calls not working on develop with Electron 9

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#973]
**Bug description:**
Skype says that no audio or video calls are supported in by browser.

**Environment:**

- Ferdi Version: build based off `develop` with Electron 9

Porting from https://github.com/getferdi/ferdi/pull/809, more details in https://github.com/getferdi/ferdi/pull/809#issuecomment-646743545.

**Comment by kris7t** [comment]
This might be connected to the `Chromium`/`Chrome`/`Electron` sniffing done by Skype to exclude Chromium users (while allowing Chrome and Edge just fine): https://github.com/Eloston/ungoogled-chromium/issues/1010#issuecomment-643740388

Obviously, this is totally unnecessary and hostile, since audio calls in Microsoft Teams work just fine with the same technology. Nevertheless, we might need to spoof PDF plugin names to solve this issue (for now, since Microsoft could probably come with and even more out-there way to exclude open source browsers from its web app).

**Comment by MurzNN** [comment]
Does this trick must work yet? Because of miss fresh Fedi release, I update my `.config/Ferdi/recipes/skype/webview.js` manually with changes from PR, but Skype still shows me call buttons disabled with "Audio and video calls are not supported on your browser" tooltip. Maybe I must do something more to fix this?

**Comment by MurzNN** [comment]
But simple trick via hardcoding user-agent in `.config/Ferdi/recipes/skype/index.js` works well, here is content of this file:
```
"use strict";

module.exports = (Franz) =>
  class Messenger extends Franz {
    overrideUserAgent() {
      return "Mozilla/5.0 (X11; Fedora; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36";
    }
  };
```

**Comment by hoangtrann** [comment]
As of today, I'm using Ferdi `5.6.1-beta.2` and Electron `13.2.2`, Chrome `91.0.4472.164` and Skype audio or microphone does not work, and for sure not the video :disappointed:
